# **Linear Regression & Regularization - Complete Guide**

## **1. Deriving the Analytical Solution**

### **Problem Setup**
We have:
- `n` data points
- `p` features
- Design matrix: `X ∈ ℝⁿˣᵖ` (with added column of 1s for intercept)
- Response vector: `y ∈ ℝⁿ`
- Coefficient vector: `β ∈ ℝᵖ`

**Goal:** Find β that minimizes squared error:
```
L(β) = ||y - Xβ||²
     = (y - Xβ)ᵀ(y - Xβ)
```

### **Derivation Steps**

#### **Step 1: Expand the loss function**
```
L(β) = yᵀy - 2βᵀXᵀy + βᵀXᵀXβ
```

#### **Step 2: Take derivative with respect to β**
```
∂L/∂β = -2Xᵀy + 2XᵀXβ
```

#### **Step 3: Set derivative to zero (for minimum)**
```
-2Xᵀy + 2XᵀXβ = 0
XᵀXβ = Xᵀy
```

#### **Step 4: Solve for β**
If `XᵀX` is invertible:
```
β̂ = (XᵀX)⁻¹Xᵀy
```

**This is the Ordinary Least Squares (OLS) solution.**

---

## **2. Adding L1 and L2 Regularization**

### **L2 Regularization (Ridge Regression)**
**Loss function:** `L(β) = ||y - Xβ||² + λ||β||²`

Where:
- `λ` = regularization strength
- `||β||²` = β₁² + β₂² + ... + βₚ² (sum of squared coefficients)

**Solution:**
```
∂L/∂β = -2Xᵀy + 2XᵀXβ + 2λβ = 0
(XᵀX + λI)β = Xᵀy
β̂_ridge = (XᵀX + λI)⁻¹Xᵀy
```

**What changes:**
- `λI` is added to `XᵀX` → always invertible (no singularity)
- Coefficients are **shrunk toward zero**
- **All coefficients remain non-zero**

### **L1 Regularization (Lasso Regression)**
**Loss function:** `L(β) = ||y - Xβ||² + λ||β||₁`

Where:
- `||β||₁` = |β₁| + |β₂| + ... + |βₚ| (sum of absolute values)

**Solution:**
No closed-form solution! Must use optimization methods:
- Coordinate descent
- Least angle regression (LARS)
- Proximal gradient methods

**What changes:**
- Some coefficients become **exactly zero**
- Performs **automatic feature selection**
- Creates **sparse solutions**

---

## **3. Why L1 Regularization Selects Features**

### **Geometric Intuition**
**L2 constraint:** Circle/sphere boundary
- Coefficients can be anywhere on/inside the sphere
- **All** coefficients typically non-zero

**L1 constraint:** Diamond boundary
- Corners of the diamond lie on axes
- Solution often at a corner → some coefficients = 0

### **Mathematical Explanation**
The absolute value in L1 has a **kink at zero**:
- Gradient is ±1 (depending on sign of β)
- At β=0, gradient can push coefficient to exactly zero and keep it there

### **Feature Selection Process**
1. **Soft thresholding:** Coefficients below λ/2 are set to zero
2. **Automatic selection:** Unimportant features get zero weight
3. **Model simplification:** Only important features remain

### **Why Many Weights = 0**
```
For Lasso, the optimality condition is:
|Xⱼᵀ(y - Xβ)| ≤ λ/2  for all j

If this holds with strict inequality for feature j:
Then βⱼ = 0
```

**In practice:**
- Features with weak relationship to y get β=0
- Redundant features get β=0
- Only strongest predictors remain

---

## **4. Making Linear Models Nonlinear**

### **Method 1: Basis Function Expansion**
Transform features using nonlinear functions:

#### **Polynomial Features**
```
Original: x
Transformed: [1, x, x², x³, ..., xᵈ]
```
**Example:** Degree 2 polynomial regression
```
ŷ = β₀ + β₁x + β₂x²
```

#### **Radial Basis Functions (RBF)**
```
φⱼ(x) = exp(-γ||x - μⱼ||²)
```
Creates localized "bumps" in feature space.

#### **Spline Basis Functions**
Piecewise polynomials with smooth connections.

### **Method 2: Kernel Methods**
**Idea:** Work in high-dimensional space without explicitly computing it.

#### **Kernel Ridge Regression**
Use kernel matrix `K` where:
```
Kᵢⱼ = k(xᵢ, xⱼ)
```
Common kernels:
- Polynomial: `k(x,z) = (xᵀz + c)ᵈ`
- RBF: `k(x,z) = exp(-γ||x-z||²)`

**Solution:** `α = (K + λI)⁻¹y`

### **Method 3: Feature Engineering**
Create new features from existing ones:

#### **Interaction Terms**
```
x₁, x₂ → also include x₁·x₂
```

#### **Transformations**
```
log(x), exp(x), √x, 1/x
```

#### **Binning**
Convert continuous to categorical:
```
Age → [0-18], [19-30], [31-50], [51+]
```

### **Practical Implementation**

```python
# Example: Polynomial features + Ridge regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge

# Create polynomial features up to degree 3
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X)

# Fit regularized linear model
model = Ridge(alpha=1.0)
model.fit(X_poly, y)

# Or using kernel ridge for RBF
from sklearn.kernel_ridge import KernelRidge
model = KernelRidge(kernel='rbf', alpha=1.0, gamma=0.1)
model.fit(X, y)
```

### **Key Considerations**

1. **Curse of dimensionality:** High-degree polynomials create many features
2. **Regularization essential:** To prevent overfitting in high-dimensional space
3. **Interpretability trade-off:** Nonlinear models are harder to interpret
4. **Computational cost:** Kernel methods scale as O(n³) or O(n²)

---

## **Summary Table**

| Method | Formula | Feature Selection | Nonlinear? |
|--------|---------|-------------------|------------|
| **OLS** | `β = (XᵀX)⁻¹Xᵀy` | No | No |
| **Ridge (L2)** | `β = (XᵀX + λI)⁻¹Xᵀy` | No (shrinkage) | No |
| **Lasso (L1)** | Numerical optimization | Yes (sparse) | No |
| **Polynomial+Ridge** | `β = (ΦᵀΦ + λI)⁻¹Φᵀy` | No | Yes |
| **Kernel Ridge** | `α = (K + λI)⁻¹y` | No | Yes |

---

## **When to Use What**

### **Use Linear/Ridge when:**
- Features already meaningful
- All features potentially relevant
- Want stable, interpretable model

### **Use Lasso when:**
- Many features, expect few to matter
- Need feature selection
- OK with some instability in selected features

### **Use Nonlinear methods when:**
- Relationships clearly curved
- Linear model underfits
- Have enough data to learn complexity

**Remember:** Always validate with train/test splits or cross-validation!

In [563]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns 
import os 
import re 
import lightgbm
import scipy
import statsmodels
from collections import Counter 

from sklearn.linear_model import Lasso , LinearRegression , Ridge
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , PolynomialFeatures , KernelCenterer
from sklearn.metrics import accuracy_score , mean_absolute_error , mean_absolute_percentage_error , mean_squared_error

In [564]:
def see(): 
 if os.path.exists('../datasets/train.json'):
  print("it is exististing dont panic ")
 else : 
  raise FileExistsError("basicaly it doesnt ecist you are on drugs ")
see()

it is exististing dont panic

In [565]:
df_train = pd.read_json('../datasets/train.json')
df_test = pd.read_json('../datasets/train.json')

In [566]:
df_test.head()
df_test.describe

<bound method NDFrame.describe of         bathrooms  bedrooms                       building_id  \
4             1.0         1  8579a0b0d54db803821a35a4a615e97a
6             1.0         2  b8e75fc949a6cd8225b455648a951712
9             1.0         2  cd759a988b8f23924b5a2058d5ab2b49
10            1.5         3  53a5b119ba8f7b61d4e010512e0dfc85
15            1.0         0  bfb9405149bfff42a92980b594c28234
...           ...       ...                               ...
124000        1.0         3  92bbbf38baadfde0576fc496bd41749c
124002        1.0         2  5565db9b7cba3603834c4aa6f2950960
124004        1.0         1  67997a128056ee1ed7d046bbb856e3c7
124008        1.0         2  3c0574a740154806c18bdf1fddd3d966
124009        1.0         3  d89f514c3ed0abaae52cba7017ac0701

                    created  \
4       2016-06-16 05:55:27
6       2016-06-01 05:44:33
9       2016-06-14 15:19:59
10      2016-06-24 07:54:24
15      2016-06-28 03:50:23
...                     ...
124000  2016-04-05 03:58:33
124002  2016-04-02 02:25:31
124004  2016-04-26 05:42:03
124008  2016-04-19 02:47:33
124009  2016-04-20 05:34:00

                                              description  \
4       Spacious 1 Bedroom 1 Bathroom in Williamsburg!...
6       BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...
9       **FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...
10      A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...
15      Over-sized Studio w abundant closets. Availabl...
...                                                   ...
124000  There is 700 square feet of recently renovated...
124002  2 bedroom apartment with updated kitchen, rece...
124004  No Brokers Fee * Never Lived 1 Bedroom 1 Bathr...
124008  Wonderful Bright Chelsea 2 Bedroom apartment o...
124009  ***PRIME MIDTOWN EAST OFF PARK AVE***TRUE 3 BE...

             display_address  \
4        145 Borinquen Place
6                  East 44th
9           East 56th Street
10       Metropolitan Avenue
15          East 34th Street
...                      ...
124000          W 171 Street
124002              Broadway
124004  210 Brighton 15th St
124008      West 21st Street
124009             E 54th St

                                                 features  latitude  \
4       [Dining Room, Pre-War, Laundry in Building, Di...   40.7108
6       [Doorman, Elevator, Laundry in Building, Dishw...   40.7513
9       [Doorman, Elevator, Laundry in Building, Laund...   40.7575
10                                                     []   40.7145
15      [Doorman, Elevator, Fitness Center, Laundry in...   40.7439
...                                                   ...       ...
124000            [Elevator, Dishwasher, Hardwood Floors]   40.8433
124002  [Common Outdoor Space, Cats Allowed, Dogs Allo...   40.8198
124004  [Dining Room, Elevator, Pre-War, Laundry in Bu...   40.5765
124008  [Pre-War, Laundry in Unit, Dishwasher, No Fee,...   40.7448
124009  [Dining Room, Elevator, Laundry in Building, D...   40.7594

        listing_id  longitude                        manager_id  \
4          7170325   -73.9539  a10db4590843d78c784171a107bdacb4
6          7092344   -73.9722  955db33477af4f40004820b4aed804a0
9          7158677   -73.9625  c8b10a317b766204f08e613cef4ce7a0
10         7211212   -73.9425  5ba989232d0489da1b5f2c45f6688adc
15         7225292   -73.9743  2c3b41f588fbb5234d8a1e885a436cfa
...            ...        ...                               ...
124000     6824800   -73.9396  a61e21da3ba18c7a3d54cfdcc247e1f8
124002     6813268   -73.9578  8f90e5e10e8a2d7cf997f016d89230eb
124004     6927093   -73.9554  a10db4590843d78c784171a107bdacb4
124008     6892816   -74.0017  c3cd45f4381ac371507090e9ffabea80
124009     6901023   -73.9712  e90f2ded843cdb2efd65ef47d9fc8029

                                                   photos  price  \
4       [https://photos.renthop.com/2/7170325_3bb5ac84...   2400
6       [https://photos.renthop.com/2/7092344_7663c19a...   3800
9       [https://photos.renthop.com/2/7158677_c897a134...   3495
10      [https://photos.renthop.com/2/7211212_1ed4542e...   3000
15      [https://photos.renthop.com/2/7225292_901f1984...   2795
...                                                   ...    ...
124000  [https://photos.renthop.com/2/6824800_0682be16...   2800
124002  [https://photos.renthop.com/2/6813268_1e6fcc32...   2395
124004  [https://photos.renthop.com/2/6927093_93a52104...   1850
124008  [https://photos.renthop.com/2/6892816_1a8d087a...   4195
124009  [https://photos.renthop.com/2/6901023_02052d90...   4280

                 street_address interest_level
4           145 Borinquen Place         medium
6                 230 East 44th            low
9          405 East 56th Street         medium
10      792 Metropolitan Avenue         medium
15         340 East 34th Street            low
...                         ...            ...
124000         620 W 171 Street            low
124002            3333 Broadway         medium
124004     210 Brighton 15th St         medium
124008     350 West 21st Street         medium
124009            123 E 54th St           high

[49352 rows x 15 columns]>

In [567]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
from collections import Counter 

df_train['interest_level'] = label.fit_transform(df_train['interest_level'])
df_train['interest_level']

4         2
6         1
9         2
10        2
15        1
         ..
124000    1
124002    2
124004    2
124008    2
124009    0
Name: interest_level, Length: 49352, dtype: int64

In [568]:
df_train['features'].apply(
    lambda lst : [re.sub(r'\s\'"','',f) for f in lst if isinstance(f,str)]
)
show = [f for x in df_train['features'] for f in x ]
show1 = Counter(show)

In [569]:
df_train['features'].to_frame().to_clipboard

<bound method NDFrame.to_clipboard of                                                  features
4       [Dining Room, Pre-War, Laundry in Building, Di...
6       [Doorman, Elevator, Laundry in Building, Dishw...
9       [Doorman, Elevator, Laundry in Building, Laund...
10                                                     []
15      [Doorman, Elevator, Fitness Center, Laundry in...
...                                                   ...
124000            [Elevator, Dishwasher, Hardwood Floors]
124002  [Common Outdoor Space, Cats Allowed, Dogs Allo...
124004  [Dining Room, Elevator, Pre-War, Laundry in Bu...
124008  [Pre-War, Laundry in Unit, Dishwasher, No Fee,...
124009  [Dining Room, Elevator, Laundry in Building, D...

[49352 rows x 1 columns]>

In [570]:
df_train['features'] = df_train['features'].apply(
    lambda lst : [re.sub(r'[\s\'"]','',f) for f in lst if isinstance(f,str)]
)

df_train = df_train[(df_train['price'] >= df_train['price'].quantile(0.01)) & (df_train['price'] <= df_train['price'].quantile(0.99))]

df_test['features'] = df_test['features'].apply(
    lambda x : [re.sub('r[\s\'"]', '', s)for s in x if isinstance(x,str)] 
)

df_test = df_test[(df_test['price'] >= df_test['price'].quantile(0.01)) & (df_test['price'] <= df_test['price'].quantile(0.99))]

In [571]:
df_train['features'].reset_index()

        index                                           features
0           4  [DiningRoom, Pre-War, LaundryinBuilding, Dishw...
1           6  [Doorman, Elevator, LaundryinBuilding, Dishwas...
2           9  [Doorman, Elevator, LaundryinBuilding, Laundry...
3          10                                                 []
4          15  [Doorman, Elevator, FitnessCenter, LaundryinBu...
...       ...                                                ...
48374  124000             [Elevator, Dishwasher, HardwoodFloors]
48375  124002  [CommonOutdoorSpace, CatsAllowed, DogsAllowed,...
48376  124004  [DiningRoom, Elevator, Pre-War, LaundryinBuild...
48377  124008  [Pre-War, LaundryinUnit, Dishwasher, NoFee, Ou...
48378  124009  [DiningRoom, Elevator, LaundryinBuilding, Dish...

[48379 rows x 2 columns]

In [572]:
all_features = [f for sub in df_train['features'] 
                    for f in sub ]
feature_count = Counter(all_features)
all_features
feature_count

Counter({'Elevator': 25398,
         'HardwoodFloors': 23159,
         'CatsAllowed': 23148,
         'DogsAllowed': 21662,
         'Doorman': 20497,
         'Dishwasher': 20095,
         'NoFee': 17806,
         'LaundryinBuilding': 16093,
         'FitnessCenter': 13000,
         'Pre-War': 8978,
         'LaundryinUnit': 8448,
         'RoofDeck': 6423,
         'OutdoorSpace': 5137,
         'DiningRoom': 4901,
         'HighSpeedInternet': 4225,
         'Balcony': 2898,
         'SwimmingPool': 2648,
         'LaundryInBuilding': 2565,
         'NewConstruction': 2507,
         'Terrace': 2179,
         'Exclusive': 2080,
         'Loft': 2042,
         'Garden/Patio': 1879,
         'WheelchairAccess': 1312,
         'CommonOutdoorSpace': 1280,
         'HARDWOOD': 880,
         'SIMPLEX': 873,
         'Fireplace': 837,
         'prewar': 820,
         'LOWRISE': 764,
         'Garage': 737,
         'LaundryRoom': 713,
         'ReducedFee': 686,
         'LaundryInUnit': 685,
         'Furnished': 668,
         'Multi-Level': 592,
         'PrivateOutdoorSpace': 501,
         'Prewar': 487,
         'PublicOutdoor': 419,
         'ParkingSpace': 412,
         'Roof-deck': 389,
         'dishwasher': 377,
         'HighCeilings': 359,
         'elevator': 343,
         'Renovated': 319,
         'Pool': 276,
         'LAUNDRY': 255,
         'GreenBuilding': 233,
         'HIGHCEILINGS': 230,
         'LIVEINSUPER': 206,
         'HighCeiling': 196,
         'WasherinUnit': 184,
         'DryerinUnit': 184,
         'Storage': 168,
         'On-sitelaundry': 167,
         'StainlessSteelAppliances': 167,
         'Concierge': 164,
         'Newlyrenovated': 153,
         'On-siteLaundry': 147,
         'Hardwood': 144,
         'Light': 144,
         'LiveInSuper': 142,
         'On-siteGarage': 140,
         'Washer/Dryer': 129,
         'GraniteKitchen': 116,
         'Gym/Fitness': 114,
         'ChildrensPlayroom': 108,
         'Petsonapproval': 107,
         'MarbleBath': 106,
         'WalkinCloset(s)': 102,
         'Subway': 101,
         'Patio': 98,
         'ResidentsLounge': 98,
         'Valet': 93,
         'Live-insuperintendent': 90,
         'Commonparking/Garage': 89,
         'Full-timedoorman': 83,
         'Parking': 82,
         'WiFiAccess': 81,
         'Live-inSuper': 81,
         'EATINKITCHEN': 81,
         'EXPOSEDBRICK': 74,
         'ShortTermAllowed': 74,
         'Lounge': 73,
         'HIGHRISE': 73,
         'doorman': 69,
         'Garden': 68,
         'Nopets': 67,
         'Bikeroom': 66,
         'CentralA/C': 61,
         'Duplex': 60,
         'Luxurybuilding': 56,
         'balcony': 55,
         'ACTUALAPT.PHOTOS': 55,
         'ResidentsGarden': 55,
         'Commonroofdeck': 53,
         'OutdoorAreas': 52,
         'ROOFDECK': 49,
         'IndoorPool': 48,
         'storage': 47,
         'Newconstruction': 47,
         'View': 45,
         'Loungeroom': 44,
         'BikeRoom': 42,
         'VirtualDoorman': 42,
         'pool': 40,
         'patio': 38,
         'building-common-outdoor-space': 37,
         'Airconditioning': 36,
         'ValetParking': 36,
         'Courtyard': 34,
         'Washer&Dryer': 33,
         'SharesOK': 33,
         'Sauna': 32,
         'WheelchairRamp': 31,
         'Gym': 31,
         'private-balcony': 30,
         'Privatebalcony': 30,
         'Live/Work': 30,
         'terrace': 30,
         'HealthClub': 29,
         'Microwave': 28,
         'FTDoorman': 28,
         'FullServiceGarage': 28,
         'Washer/Dryerinbuilding': 28,
         'OutdoorEntertainmentSpace': 28,
         'Live-InSuperintendent': 28,
         'Laundry': 27,
         'gym': 27,
         'ExposedBrick': 26,
         'Post-War': 25,
         'On-siteParkingLot': 25,
         'BasementStorage': 25,
         'Privateoutdoorspace': 24,
         'garden': 23,
         'BROWNSTONE': 23,
         'HiRise': 23,
         'In-UnitWasher/Dryer': 23,
         'private-outdoor-space': 21,
         'Commonterrace': 21,
         'PostWar': 21,
         'on-sitesuper': 21,
         'ConciergeService': 20,
         'MIDRISE': 20,
         'Hardwoodfloors': 19,
         'PetFriendly': 18,
         'DECORATIVEFIREPLACE': 17,
         'Sublet': 17,
         'On-SiteParking': 17,
         'WALKINCLOSET': 17,
         'GuarantorsAccepted': 16,
         'Privatebackyard': 16,
         'AttendedLobby': 16,
         'RooftopTerrace': 16,
         'Privateterrace': 16,
         'BusinessCenter': 16,
         'storageroom': 16,
         'NOFEE': 15,
         'Commongarden': 15,
         'assigned-parking-space': 15,
         'Privateparking': 15,
         'Deck': 15,
         'High-speedInternet': 15,
         'Terraces/Balconies': 14,
         'Commonbackyard': 14,
         'playroom/nursery': 14,
         'PackageRoom': 13,
         'Flex-2': 13,
         'Cable/SatelliteTV': 12,
         'EatInKitchen': 12,
         'ActualApt.Photos': 12,
         'CommunityRecreationFacilities': 12,
         'OutdoorPool': 12,
         'view': 12,
         'Skylight': 11,
         'DININGROOM': 11,
         'Roofdeck': 11,
         'LaundryOnFloor': 11,
         'Sharedbackyard': 11,
         'Washer/DryerinUnit': 11,
         'garage': 11,
         'MailRoom': 11,
         'BALCONY': 10,
         'Live/work': 10,
         'GymInBuilding': 9,
         'CentralAir': 9,
         'renovated': 9,
         'MarbleBathroom': 9,
         'Fireplaces': 9,
         'BikeStorage': 9,
         'Eat-inKitchen': 9,
         'DecorativeFireplace': 9,
         'Multi-level': 9,
         'PrivateDeck': 9,
         'TenantLounge': 9,
         'CentralAC': 9,
         'Sundeck': 9,
         'Highceilings': 8,
         'hardwoodfloors': 8,
         'MediaRoom': 8,
         '24/7Concierge': 8,
         'RooftopDeck': 8,
         'ScreeningRoom': 8,
         'Valetservicesincludingdrycleaning': 8,
         'laundry&housekeeping': 8,
         'Privatelaundryroomoneveryfloor': 8,
         'BACKYARD': 8,
         'valet': 8,
         'ValetServices': 8,
         'highceilings': 8,
         'Playroom': 7,
         'VideoIntercom': 7,
         'WiFi': 7,
         '24/7Doorman': 7,
         'Washer/DryerHookup': 7,
         'ParkingAvailable': 7,
         'GutRenovated': 7,
         'pets': 7,
         'fireplace': 7,
         'DUPLEX': 7,
         'Allutilitiesincluded': 7,
         'exposedbrick': 7,
         'Jacuzzi': 7,
         'centralac': 7,
         'GarbageDisposal': 7,
         'Cityview': 7,
         'petsallowed': 7,
         'TONSOFNATURALLIGHT': 7,
         'QUEENSIZEDROOMS': 7,
         'CLOSETSGALORE!': 7,
         'CHEFSKITCHEN': 7,
         'CONDOFINISHES': 7,
         'Roofaccess': 6,
         'Laundryinbuilding': 6,
         'Backyard': 6,
         'Walk-InCloset': 6,
         'On-sitesuper': 6,
         'PetsAllowed': 6,
         'Flex-3': 6,
         'StorageAvailable': 6,
         'Wood-burningFireplace': 6,
         '24hrdoorman': 5,
         'Housekeepingservice': 5,
         'PrivateTerrace': 5,
         'BreakfastBar': 5,
         'NewRenovation': 5,
         'lounge': 5,
         'roofdeck': 5,
         'PartyRoom': 5,
         'MagnificentVenetian-Style': 5,
         'Fullyequipped': 5,
         'state-of-the-artfitnesscenter': 5,
         'On-siteParkingavailable': 5,
         'On-siteATMMachine': 5,
         'OutdoorroofdeckoverlookingNewYorkHarborandBatteryPark': 5,
         'StorageFacilitiesavailable': 5,
         'RENOVATED': 5,
         'Privategarden': 5,
         'Exposedbrick': 5,
         'deck': 5,
         'Privateroofdeck': 5,
         'LargeLivingRoom': 5,
         'ActualPhotos!': 5,
         'CinemaRoom': 5,
         'Parkview': 5,
         'VirtualTour': 5,
         'Penthouse': 5,
         'FitnessRoom': 5,
         'S/Sappliances': 5,
         'BilliardsRoom': 5,
         'parking': 5,
         'CrownMoldings': 5,
         'videointercom': 5,
         'Part-timedoorman': 5,
         'Granitecountertops': 4,
         'HomeOffice': 4,
         'NewlyRenovated': 4,
         'Screeningroom': 4,
         'On-siteparking': 4,
         'Pets:Cats/SmallDogs': 4,
         'businesscenter': 4,
         'HARDWOODFLOORS': 4,
         'GARDEN': 4,
         'sauna': 4,
         'Bright': 4,
         'Closetosubway': 4,
         'Spacious': 4,
         'GraniteCounterTops': 4,
         'laundryroom': 4,
         'Yard': 4,
         'ValetService': 4,
         'microwave': 4,
         'RenovatedKitchen': 4,
         'Cableready': 4,
         'rooftopdeck': 4,
         'commonstorage': 4,
         'OneMonthFree': 4,
         'walk-up': 4,
         'Call/TextAbrahamCaro@917-373-0862': 4,
         'PrivateRoofDeck': 4,
         'YogaClasses': 4,
         'LiveinSuper': 4,
         'Live-InSuper': 4,
         'fitnesscenter': 3,
         'Sharedgarden': 3,
         'Packageservice': 3,
         'FreeWifi': 3,
         'StainlessSteel': 3,
         'GraniteCounters': 3,
         'DiplomatsOK': 3,
         'Package&grocerydeliverystorage': 3,
         'Fullsizegym': 3,
         'Yoga/dancestudio': 3,
         'Movietheater': 3,
         'Childrenplayroom': 3,
         'Gardeningareawithrentableplots': 3,
         'Bike&strollerstorage': 3,
         'Petgroomingroom': 3,
         'Stunningroofdeckwithbreathtakingviews': 3,
         'Roofgrillingarea': 3,
         'Rentable': 3,
         'fullyequippedchef’skitchenwithprivateroofdeck': 3,
         'Partyroom': 3,
         'DecoBrickWall': 3,
         'walkincloset': 3,
         'FrenchDoors': 3,
         'LargeLiving-room': 3,
         'Bright&Sunny': 3,
         'GasIncluded': 3,
         'LowFee': 3,
         'LargeWindowswithLotsofNaturalLight': 3,
         'childrensplayroom': 3,
         'Skylights': 3,
         'QueenSizedBedrooms': 3,
         'Allpetsok': 3,
         'Bikestorage': 3,
         'Gameroom': 3,
         'On-siteSuper': 3,
         'OakFloors': 3,
         'StorageSpace': 3,
         'On-sitelifestyleconciergebyLuxuryAttaché': 3,
         'Elegantglass-enclosedprivateloungewithmagnificentriverviews': 3,
         'Billiardstableandwetbar': 3,
         'Fully-equippedClubfitnesscenter': 3,
         'Clubsundeckhasspectacularcityandriverviews': 3,
         'ComplimentarySundaybrunch': 3,
         'On-siteparkingavailable': 3,
         'FreeWiFiinClublounge': 3,
         'RecessedLighting': 3,
         'UtilitiesIncluded': 3,
         'Bluetooth': 3,
         'OriginalDetails': 3,
         'Drycleaningservice': 3,
         'UnassignedPaidparkingavailablenearby': 3,
         'Diningroom': 3,
         '24/7DoormanConcierge': 3,
         'SpaServices': 3,
         'ColdStorage': 3,
         'bikeroom': 3,
         'billiardsroom': 3,
         'waterfiltrationsystem': 3,
         'fitnessfacility': 3,
         'exercisestudio': 3,
         'steamroom': 3,
         'privatestorage': 3,
         'DW': 3,
         'BrandNew': 3,
         'WindowBath': 3,
         'Privateroofaccess': 3,
         'SkylightAtrium': 3,
         'DuplexLounge': 3,
         'On-SiteAttendedGarage': 3,
         'ClosetoSubway': 3,
         'townhouse': 3,
         'Laundryoneveryfloor': 3,
         'LiveWork': 3,
         'HighSpeedInternetAvailable': 3,
         'ValetLaundry': 3,
         'DryCleaningService': 3,
         'OutdoorBasketballCourt': 3,
         'YogaRoom': 3,
         'decofireplace': 3,
         'Children’sPlayroom': 3,
         '24-hourdoorman': 3,
         'Wi-FiAccess': 3,
         'Washer/DryerinBldg': 3,
         'stainlesssteelappliances': 3,
         'MultiLevel': 3,
         'UndergroundParking': 3,
         'RoofDeckwithrealgrass': 3,
         'RentStabalized': 3,
         'BilliardsLounge': 3,
         'OutdoorBBQs': 3,
         'LeedCertified': 3,
         '24HRDoorman': 3,
         'Convinienttoallmajortransportation': 3,
         'OutstandingShopping': 3,
         'separatekitchen': 3,
         'PreWar': 3,
         'Builtinmicrowave': 2,
         'FinishedBasement': 2,
         'KingSizedBedroom': 2,
         'childrensroom': 2,
         'NaturalLight': 2,
         'Riverview': 2,
         'Stainlesssteelappliances': 2,
         'KingSizeBedrooms': 2,
         'UnassignedPaidparkingavailable': 2,
         'LargeLivingroom': 2,
         'Sunny': 2,
         'LotsofLight': 2,
         'HardwoodFloor': 2,
         'Live-insuper': 2,
         'privatebackyard': 2,
         'inunitwasheranddryer': 2,
         'UnionSquare': 2,
         'HEAT/HOTWATERINCLUDED': 2,
         'Extraroom': 2,
         'HeatIncluded': 2,
         'Eat-inkitchen': 2,
         'Laundryroomoneveryfloor.Healthclub': 2,
         'indoorswimmingpool': 2,
         'sundeckwithBBQgrills': 2,
         'mistingshowerandresidentloungeavailable.': 2,
         'floortoceilingwindows': 2,
         'Mint': 2,
         'AFullServiceluxuryHighrise': 2,
         'ExposedBrickWall': 2,
         'Petsallowed': 2,
         'PokerTable': 2,
         'Childrensplayroom': 2,
         'stainlesssteel': 2,
         'WorkingFireplace': 2,
         'SuperOn-Site': 2,
         'FreeGym': 2,
         'GrandCentral': 2,
         'closetspace': 2,
         'Southernexposure': 2,
         'SunnySouthernExposure': 2,
         'Storagespace': 2,
         'Skylineview': 2,
         'GraniteCountertops': 2,
         'StainlessAppliances': 2,
         'DISHWASHER': 2,
         'Flex-1': 2,
         'GreatClosetSpace': 2,
         'Onesmalldogokonapproval': 2,
         'Twenty-fourhourconciergeanddoorman': 2,
         'ExtraRoom': 2,
         'SouthernExposure': 2,
         'QueenSizedBedroom': 2,
         'ExtraClosetSpace': 2,
         'DishWasher': 2,
         'DecoFireplace': 2,
         'valetparking': 2,
         'ExtraStorage': 2,
         'Garage.': 2,
         'Inunitwasheranddryer': 2,
         'loungearea': 2,
         'Fitnesscenter': 2,
         'RenovatedBathroom': 2,
         'Closets': 2,
         '2FullBaths': 2,
         'AFullserviceLuxuryHighrise': 2,
         '<null>': 2,
         'BUILT-INSPEAKERSYSTEM': 2,
         'Largewindows': 2,
         'kitchenisland': 2,
         'Breakfastbar': 2,
         'MediaScreeningRoom': 2,
         'Exercise/YogaStudio': 2,
         'RoofDeckwithGrills': 2,
         'Washer/DryerIn-Unit': 2,
         'RecessedLighting.': 2,
         'CentralHeat': 2,
         'StainlessSteelKitchen': 2,
         'Huge': 2,
         'onemonthfreerent': 2,
         'RentStabilized': 2,
         'GramercyPark': 2,
         'FullserviceLuxuryHighrise': 2,
         '24HourDoorman': 2,
         'State-of-the-ArtCardioandFitnessClub': 2,
         'On-siteResidentManager': 2,
         'ExpansiveSundeck': 2,
         'TenantStorage': 2,
         'OpenLayout': 2,
         'WaterViews': 2,
         'NoFee!': 2,
         'Pre-warCharm': 2,
         'Foyer': 2,
         'SSAKitchen': 2,
         'Intercom': 2,
         'rooftop': 2,
         'MW': 2,
         'WindowKitchen': 2,
         'KingSizeBedroom': 2,
         'On-SiteSuper': 2,
         'Balconiesinbothbedrooms': 2,
         '24/7Full-TimeDoormanConcierge': 2,
         'Shortterm': 2,
         'newlyrenovated': 2,
         'heathotwaterincluded': 2,
         'hugeroom': 2,
         'ComplimentaryContinentalBreakfast': 2,
         'ElectronicRentPayment': 2,
         'WifiinResidentLounge': 2,
         'StainlessSteelappliances': 2,
         'NOPETS': 2,
         'EatinKitchen': 2,
         'Businesscenter': 2,
         'Marblebath': 2,
         'SSappliances': 2,
         'Chefskitchen': 2,
         'elevator&Laundry': 2,
         'PRIVATEBALCONY': 2,
         'shareok': 2,
         'KingBedrooms': 2,
         'housekeeping': 2,
         'Pets-casebycase.': 2,
         'SPACE': 2,
         'LIGHT': 2,
         'StainlessStealAppliances': 2,
         '1MonthFree': 2,
         'HardwoodFlooring': 2,
         'Full-servicecondominium': 2,
         'Garageattached': 2,
         'Storageroom': 2,
         'Loungespaces': 2,
         'Healthclubwithpoolonthetopfloor': 2,
         'YogaandSpinStudios': 2,
         'LargeWindowsw/lotsofNaturalLight': 2,
         'Onsitesuper': 2,
         'CornerUnit': 2,
         'ClosetoTransit': 2,
         'CommonStorage': 2,
         'GraniteCounter': 2,
         'ALLUTILITIESINCLUDED': 2,
         'Triplex': 2,
         'ManhattanViews': 2,
         'Available05/01/16': 2,
         'LaundryinSomeUnits': 2,
         'Utilitiesincluded': 1,
         'PrivateEntrances': 1,
         'TopFloorUnit': 1,
         'XXLWindows': 1,
         'petfriendly': 1,
         'waterview': 1,
         '24hrdoormen': 1,
         'packageservice': 1,
         'drycleaningservice': 1,
         'SleepLoft': 1,
         'ownentrance': 1,
         'oakcabinets': 1,
         '**HOLYNOFEEDEALBATMAN!*OVERSIZED2BRHOME*SPARKLINGCLEAN&BRITE*HEARTOFGREENPOINT*NEARTHEPARK&TRAINS**': 1,
         'RecreationalRoom': 1,
         'Townhouse': 1,
         'dry-cleaningservice': 1,
         'Washer': 1,
         '!!!!LOWFEE!!!!': 1,
         '**CHELSEABABY!*MASSIVE2BRSUPERSHARE*ALLMODERN&NEW*ELEV/LNDRYBLDG**': 1,
         'LoftArea': 1,
         'Flextwobed': 1,
         'Superintendentlivesin': 1,
         '**SPRAWLINGSTUDIOHOME*DISHWASHER*EXPOSEDBRICK*GUTRENOVATED*PETSOK*STEPSTOTHEPARK**': 1,
         'Control&payforyourownheatwithyourownthermostat': 1,
         'NOalternatesideparkingrulesinneighborhood': 1,
         'Previoustenantfoundeasyon-streetparking.': 1,
         'CitiBikeStation': 1,
         'GarageParking!': 1,
         '**COURTSQUAREGEM!*SPRAWLINGSUNDRENCHED2BRHOME*CUSTOMFINISHES*DISHWASHER*FIREPLACES*EAT-INKITCHEN*BAYWINDOWS**': 1,
         'Recentlyrenovated': 1,
         '2blocksawayfromUnionSquare': 1,
         'ComboWasherDryer': 1,
         'BridgeView': 1,
         'Sharedyard': 1,
         'Outdoorplayarea': 1,
         'Washeranddryerinunit': 1,
         'Walk-incloset': 1,
         'Childrensroom': 1,
         'build-inMicrowave-oven': 1,
         'ceiling-fan...': 1,
         '**UNIQUEFIND!*SPRAWLING2BRSUPERSHARE*WALLSOFWINDOWS*STUNNINGRENOVATIONS*2BLKSTOBEDFORDLSTOP**': 1,
         'ExpansiveLiving-room': 1,
         '**OVERSIZED1BRHOME*GUTRENOVATED*PERFECTNATURALLIGHT*HEARTOFCHELSEA*PETSOK**': 1,
         'AfullserviceLuxuryhighrise': 1,
         'Queen&KingSizeBedrooms': 1,
         '4thoffCharles': 1,
         'ALLNEW': 1,
         'LoftLike': 1,
         'BigRooms': 1,
         'TheMostSoughtafterLocation': 1,
         'petsuponapproval': 1,
         'ResidentSuperinthebuilding': 1,
         '**OVERSIZED2BRSUPERSHARE*FRENCHDOORS*SSEAT-INKITCHEN*MRCLEANAPPROVED*HEARTOFMIDTOWN!**': 1,
         'Diswasher': 1,
         'ELEVATOR/LAUNDRY/SOCLOSETOTHE6$2450!!': 1,
         'HotWaterInc.HUGEWalk-InClosetorExtraRoom!': 1,
         'AirConditioning': 1,
         'NearSubway': 1,
         'NearPRATT': 1,
         '•On-sitelifestyleconciergebyLuxuryAttaché•24/7Doorman•Stateoftheartcardiovascularandweighttrainingequipment•24-hourvaletparkinggarage•Valetservicesincludingdrycleaning': 1,
         'laundry&housekeeping•MarcClubincludesacinemaroom': 1,
         'exclusiveresidentiallounge&Café•Spaciousandbreathtakingfullylandscaped10': 1,
         '000-squarefootsundeck•FreeWiFiinMarcClub': 1,
         '**DOUBLEDUPLEXDEAL!*SPRAWLING3BRHOME*1.5BATHS*PRIVATEDECK&BALCONY!*EAT-INKITCHEN*WASHER//DRYER*ALLMODERNNEW!**': 1,
         'Kingsizebedroom': 1,
         'FLEXIBLEVIEWINGTIMES': 1,
         '1.5Bath': 1,
         'eatinkitchen': 1,
         'MintCondition': 1,
         '12thSt&3rdAve': 1,
         '**CLASSYCONV2BRDUPLEXDREAM!*ROOMTOENTERTAIN*LNDRYBLDG*CATSOK*HEARTOFTHEVILLAGE**': 1,
         '**SASSYSOHOSTEAL!*NOFEE!*SPRAWLINGSTUDIOHOME*GOURMETKITCHEN*HUGECLOSETS*ELEVBLDG**': 1,
         'AllUtilitiesincluded': 1,
         'NearTransportation': 1,
         'AC': 1,
         'Separatekitchen': 1,
         'Sorrynopets': 1,
         'EqualKing-SizeBedrooms': 1,
         'BrandNewSSKitchen': 1,
         'PolishedHardwoodFloors': 1,
         'SparklingMarbleBathroom': 1,

In [573]:
unique = set(feature_count)
len(unique)

1528

In [574]:
top20 = [feature[0] for feature in feature_count.most_common(21)]
top20

['Elevator',
 'HardwoodFloors',
 'CatsAllowed',
 'DogsAllowed',
 'Doorman',
 'Dishwasher',
 'NoFee',
 'LaundryinBuilding',
 'FitnessCenter',
 'Pre-War',
 'LaundryinUnit',
 'RoofDeck',
 'OutdoorSpace',
 'DiningRoom',
 'HighSpeedInternet',
 'Balcony',
 'SwimmingPool',
 'LaundryInBuilding',
 'NewConstruction',
 'Terrace',
 'Exclusive']

In [575]:
for feature in top20:
    df_train[feature] = df_train['features'].apply(lambda x: 1 if feature in x else 0)
    df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)

C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)
C:\Users\hosse\AppData\Local\Temp\ipykernel_47084\1600368820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test[feature] = df_test['features'].apply(lambda x: 1 if feature in x else 0)

In [576]:
df_train

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,...,RoofDeck,OutdoorSpace,DiningRoom,HighSpeedInternet,Balcony,SwimmingPool,LaundryInBuilding,NewConstruction,Terrace,Exclusive
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[DiningRoom, Pre-War, LaundryinBuilding, Dishw...",40.7108,7170325,-73.9539,...,0,0,1,0,0,0,0,0,0,0
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, LaundryinBuilding, Dishwas...",40.7513,7092344,-73.9722,...,0,0,0,0,0,0,0,0,0,0
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, LaundryinBuilding, Laundry...",40.7575,7158677,-73.9625,...,0,0,0,0,0,0,0,0,0,0
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,...,0,0,0,0,0,0,0,0,0,0
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, FitnessCenter, LaundryinBu...",40.7439,7225292,-73.9743,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,1.0,3,92bbbf38baadfde0576fc496bd41749c,2016-04-05 03:58:33,There is 700 square feet of recently renovated...,W 171 Street,"[Elevator, Dishwasher, HardwoodFloors]",40.8433,6824800,-73.9396,...,0,0,0,0,0,0,0,0,0,0
124002,1.0,2,5565db9b7cba3603834c4aa6f2950960,2016-04-02 02:25:31,"2 bedroom apartment with updated kitchen, rece...",Broadway,"[CommonOutdoorSpace, CatsAllowed, DogsAllowed,...",40.8198,6813268,-73.9578,...,0,0,0,0,0,0,1,0,0,0
124004,1.0,1,67997a128056ee1ed7d046bbb856e3c7,2016-04-26 05:42:03,No Brokers Fee * Never Lived 1 Bedroom 1 Bathr...,210 Brighton 15th St,"[DiningRoom, Elevator, Pre-War, LaundryinBuild...",40.5765,6927093,-73.9554,...,0,0,1,0,0,0,0,0,0,0
124008,1.0,2,3c0574a740154806c18bdf1fddd3d966,2016-04-19 02:47:33,Wonderful Bright Chelsea 2 Bedroom apartment o...,West 21st Street,"[Pre-War, LaundryinUnit, Dishwasher, NoFee, Ou...",40.7448,6892816,-74.0017,...,0,1,0,0,0,0,0,0,0,0
124009,1.0,3,d89f514c3ed0abaae52cba7017ac0701,2016-04-20 05:34:00,***PRIME MIDTOWN EAST OFF PARK AVE***TRUE 3 BE...,E 54th St,"[DiningRoom, Elevator, LaundryinBuilding, Dish...",40.7594,6901023,-73.9712,...,0,0,1,0,0,0,0,0,0,0

In [577]:
df_final = ['bathrooms', 'bedrooms'] + top20
df_final

['bathrooms',
 'bedrooms',
 'Elevator',
 'HardwoodFloors',
 'CatsAllowed',
 'DogsAllowed',
 'Doorman',
 'Dishwasher',
 'NoFee',
 'LaundryinBuilding',
 'FitnessCenter',
 'Pre-War',
 'LaundryinUnit',
 'RoofDeck',
 'OutdoorSpace',
 'DiningRoom',
 'HighSpeedInternet',
 'Balcony',
 'SwimmingPool',
 'LaundryInBuilding',
 'NewConstruction',
 'Terrace',
 'Exclusive']

In [578]:
x_train  = df_train[df_final]
y_tarin = df_train['price']
X_test = df_train[df_final]
y_test = df_test['price']

In [579]:
class regression():
    def __init__(self,method ='sgd',learning_rate = 0.001,iteration= 100, seed= 21,batch_size = 32 ):
        self.learning_rate =learning_rate
        self.iteration= iteration
        self.seed = seed
        self.w = None
        self.method = method
        self.batch_size = batch_size
    def linearregression(self,x,y):
        #first we need to make our intercept and then we need to caucalte our rate
        w0 = x.shape[0]
        # with the c_ we target the intercept like if our x be ([2,3],[3,4]) after the c_(np.ones((w0,1)))we creat the 1 at first of our arrays as interecept or b  
        xb = np.c_[np.ones((w0,1)),x]
        # in here we basically count the w = (x . x.t)^-1 . x.t . y
        self.w = np.linalg.pinv(xb.T @ xb) @ xb.T @ y

    def fit_gb(self,x,y):
        np.random.seed(self.seed)
        w0 = x.shape[0]
        xb = np.c_[np.ones((w0,1)),x]
        self.w = np.zeros(xb.shape[1])
        n = xb.shape[0]
        for i in range(self.iteration):
            y_pred = xb @ self.w
            gred = (2/n) * (xb.T @ (y_pred - y))
            self.w = self.learning_rate * gred
    def _fit_sgred(self,x,y):
        np.random.seed(self.seed)
        
        Xb = np.c_[np.ones((x.shape[0], 1)), x]
        self.w = np.zeros(Xb.shape[1], dtype=np.float64)
        n = Xb.shape[0]

        for x in range(self.iteration):
            indices = np.random.permutation(n)
            y_shuffled = y[indices]
            Xb_shuffled = Xb[indices]
        for i in range(0, n, self.batch_size):
                X_batch = Xb_shuffled[i: i+self.batch_size]
                y_batch = y_shuffled[i: i+self.batch_size]
                y_pred = X_batch @ self.w
                grad = (2 / len(X_batch)) * (X_batch.T @ (y_pred - y_batch))
                self.w -= self.learning_rate * grad

    def fit(self, X, y):
        if self.method == 'analytic':
            self.linearregression(X, y)
        elif self.method == 'gd':
            self.fit_gb(X, y)
        elif self.method == 'sgd':
            self._fit_sgred(X, y)

    def predict(self,X):
        X = np.c_[np.ones((X.shape[0], 1)), X]
        return X.dot(self.w)

In [580]:
lr3  = regression(method='sgd')
lr3.fit(x_train,y_tarin)

KeyError: '[1270, 48361, 10115, 5098, 28942, 16139, 41754, 38872, 41147, 3107, 46657, 32999, 23487, 34711, 24352, 22202, 3435, 22353, 15416, 47795, 7419, 34628, 37237, 43600, 4089, 22983, 27299, 27771, 39060, 34207, 17479, 29431, 33353, 13622, 10457, 17344, 30315, 22761, 34515, 37346, 39823, 2553, 27380, 22092, 22921, 31607, 36684, 9463, 16179, 3630, 39965, 20229, 29701, 3078, 46968, 1098, 29266, 30681, 16201, 3992, 6872, 10840, 8298, 21309, 21439, 3343, 35318, 47411, 16448, 33929, 24619, 47473, 18713, 7, 45861, 31795, 3525, 7746, 29260, 41424, 29563, 43088, 33341, 36824, 5033, 35208, 31619, 11725, 32081, 34810, 18022, 16099, 19015, 23689, 18929, 31743, 29028, 12684, 3203, 17334, 6726, 5004, 9378, 43105, 11922, 29473, 3366, 4707, 46455, 5896, 43951, 9217, 18974, 41613, 20469, 23784, 42722, 11294, 16699, 35305, 40356, 36623, 24470, 42580, 38978, 4238, 25429, 46411, 2657, 33857, 17210, 15350, 18591, 16319, 20006, 29189, 35113, 24333, 44362, 39491, 10461, 42946, 1575, 40731, 38342, 16391, 33406, 16524, 16837, 8022, 39085, 6612, 6655, 35385, 13985, 43481, 25267, 37100, 21216, 45161, 180, 19170, 29085, 31091, 8266, 42646, 22343, 44907, 24026, 48306, 40400, 32773, 29239, 27929, 27766, 39443, 34122, 1524, 19731, 18692, 4378, 12525, 46645, 6715, 1919, 44228, 1832, 43266, 39500, 21212, 3857, 37974, 2494, 46610, 24108, 15293, 2994, 19090, 39069, 36110, 46161, 12821, 26995, 6886, 13351, 27992, 32281, 44646, 24464, 30180, 21752, 4881, 6993, 24336, 10292, 31481, 1616, 2828, 19256, 27256, 48131, 13362, 30149, 36991, 32329, 5457, 22662, 24261, 8037, 18939, 43000, 21791, 26259, 25813, 29876, 33460, 32611, 31441, 26948, 20059, 12082, 22559, 29909, 17358, 28428, 43191, 23417, 40066, 4776, 34721, 46421, 37124, 24862, 1642, 35198, 3576, 39877, 34576, 1419, 46106, 20115, 36640, 5635, 4352, 1331, 48032, 16276, 23735, 22498, 35860, 30606, 7792, 31860, 38900, 30849, 38262, 27131, 15702, 34220, 48310, 4419, 10675, 10719, 3016, 8039, 213, 28694, 43029, 12013, 42635, 9373, 38485, 3368, 39946, 41894, 43583, 24787, 14739, 15762, 45634, 11809, 1900, 33812, 6133, 1355, 42129, 28058, 18642, 40366, 5929, 34958, 21109, 47384, 24741, 46813, 47622, 37913, 10389, 47664, 9028, 22171, 22234, 20313, 9036, 46974, 14019, 9192, 44190, 32466, 7577, 46309, 40196, 3552, 41801, 43941, 37347, 31248, 31589, 9890, 13211, 35014, 16403, 32458, 44029, 46653, 31112, 18156, 9816, 20277, 24367, 46376, 14367, 31155, 45949, 42690, 47460, 16182, 17301, 43566, 19035, 38970, 25664, 28777, 33896, 41749, 18703, 47812, 44048, 41848, 13637, 44243, 45137, 8271, 36459, 42525, 2885, 12100, 44023, 4304, 12890, 33679, 33709, 46692, 31676, 31312, 39698, 14319, 45265, 8903, 34774, 33525, 23078, 19422, 43817, 25128, 47221, 7445, 25088, 30579, 10186, 14847, 10798, 43902, 10939, 21025, 24606, 19296, 10441, 39464, 32789, 46962, 17138, 37896, 5080, 24, 20708, 29061, 3603, 4152, 40933, 2856, 9088, 9567, 36213, 37860, 38353, 27678, 14495, 43544, 8573, 5028, 3549, 306, 46980, 48117, 45382, 30679, 11357, 28290, 21081, 34004, 21189, 9346, 19601, 4943, 1615, 19527, 10940, 38805, 10884, 8865, 44587, 48326, 17667, 643, 2996, 3334, 43933, 982, 4017, 45755, 9050, 35547, 42816, 5156, 33596, 3028, 11844, 24430, 33684, 25523, 8664, 17254, 7444, 42528, 20306, 26275, 32016, 4120, 11670, 8313, 48262, 39904, 31479, 31267, 34550, 13790, 23532, 31127, 3703, 12356, 1005, 20885, 37044, 19863, 32179, 25539, 10904, 42813, 38629, 45066, 16239, 44891, 22212, 3495, 30593, 25550, 18456, 22436, 23734, 9107, 23599, 42459, 22, 34717, 42247, 39108, 48342, 39356, 3221, 39364, 31042, 10132, 35754, 39137, 47973, 18325, 35301, 27390, 28362, 41092, 27742, 45934, 45944, 28652, 16387, 17408, 24239, 27428, 31594, 29868, 8667, 40686, 7533, 6524, 42366, 28627, 12192, 28603, 30527, 14445, 33240, 25935, 37469, 12291, 22221, 41231, 19022, 25839, 14588, 8455, 31207, 37808, 40182, 14934, 32582, 20109, 47269, 30995, 12191, 16220, 38597, 34886, 32519, 2641, 14987, 33376, 14096, 15589, 26761, 39160, 42732, 44262, 8028, 29610, 31747, 25621, 43559, 1931, 37992, 40642, 13009, 33685, 37374, 26276, 46547, 6914, 37629, 41675, 44498, 9090, 11850, 2274, 9475, 1990, 23616, 36781, 31409, 10894, 27825, 38830, 26162, 14286, 30618, 23494, 19897, 19366, 7979, 39474, 38117, 27239, 23468, 28204, 26041, 10502, 18990, 37861, 44284, 30816, 5899, 25159, 47355, 13837, 35265, 2647, 2402, 30000, 25496, 24517, 30575, 24762, 31382, 34358, 34137, 2260, 47703, 25186, 5608, 36927, 22322, 38739, 16556, 21860, 27047, 45073, 39788, 8027, 33971, 36521, 9302, 48237, 46291, 41397, 45452, 35090, 47452, 8570, 21051, 31451, 47245, 22468, 12722, 40236, 6329, 41049, 13703, 4318, 44942, 34146, 45866, 25112, 45399, 15149, 18812, 33311, 21122, 26827, 21330, 8519, 42989, 23186, 22187, 3590, 22887, 21099, 4464, 29002, 1724, 5436, 33132, 20385, 6567, 47486, 37275, 20741, 33826, 21156, 14553, 8003, 23049, 37279, 22959, 41263, 12298, 39690, 47508, 40921, 27841, 7130, 46890, 48119, 46675, 14752, 44593, 6179, 2389, 14904, 24967, 45708, 35765, 966, 7082, 34640, 42914, 8389, 25185, 18087, 46761, 6049, 18295, 1104, 4295, 13074, 40849, 45321, 14983, 44842, 6582, 2052, 24989, 9156, 26489, 3018, 19579, 17551, 17137, 42980, 48251, 38483, 23321, 44251, 35157, 29765, 37958, 14605, 20525, 40395, 47286, 42841, 36190, 11908, 30505, 24452, 27311, 32294, 39937, 42457, 3744, 43215, 24694, 22866, 34818, 42463, 29763, 47910, 5058, 36524, 18620, 14631, 14016, 45663, 3065, 43562, 15897, 39915, 6910, 40176, 18936, 14180, 19873, 46458, 38796, 33593, 43401, 10688, 18964, 4054, 44542, 37664, 31604, 14975, 37727, 12853, 12945, 31072, 372, 25797, 36250, 19411, 44755, 13737, 9321, 37376, 14347, 13675, 9189, 3178, 30338, 1205, 24149, 35634, 955, 9089, 37459, 11025, 19811, 15245, 15126, 46606, 31086, 6544, 20735, 20091, 17716, 29102, 47671, 48337, 543, 10658, 12035, 4321, 4503, 32122, 20912, 47976, 31722, 18175, 19084, 2087, 16538, 23912, 28956, 41753, 45021, 40073, 40995, 42420, 31101, 2633, 37968, 28644, 10744, 23253, 41141, 15208, 44510, 33476, 29150, 28655, 37525, 10088, 22297, 15106, 10337, 44476, 20855, 3349, 13013, 43970, 14085, 38741, 10951, 35631, 31276, 23173, 405, 41961, 8292, 38479, 28805, 26214, 18861, 9659, 24002, 20060, 11923, 1865, 31025, 26960, 32632, 8400, 44876, 18885, 24566, 8246, 14110, 3323, 19075, 6119, 20225, 46169, 32127, 43295, 46149, 40477, 46468, 28621, 12953, 21818, 43361, 39197, 42234, 13996, 14159, 1555, 10512, 24111, 23530, 36652, 44849, 13885, 42535, 13905, 21648, 27636, 21164, 6307, 34558, 34128, 31660, 12427, 33257, 18978, 20687, 39165, 13312, 28771, 10638, 41159, 39555, 25434, 31730, 5503, 44199, 30773, 14065, 209, 35096, 12976, 39896, 3027, 19432, 30826, 3663, 33496, 9272, 15473, 46027, 19176, 1863, 3826, 29938, 35612, 43243, 15644, 33016, 12271, 40749, 38265, 42740, 16483, 7452, 8610, 37849, 4647, 34574, 29405, 45475, 42805, 13909, 10016, 20998, 16056, 4891, 2980, 2199, 45619, 48028, 1726, 19828, 37033, 25074, 301, 8522, 45226, 25925, 21836, 25385, 30774, 32011, 29387, 30045, 7045, 28095, 16867, 44619, 33046, 35595, 11998, 45541, 347, 2303, 2600, 13120, 44259, 39778, 40019, 4052, 38451, 17644, 16567, 39363, 17264, 42803, 23019, 37874, 24300, 21515, 22142, 11147, 8416, 40616, 39678, 30597, 38812, 22040, 30823, 3288, 33339, 18991, 35593, 4348, 30535, 10739, 9854, 24320, 45043, 36057, 27317, 14602, 26209, 32914, 1248, 9079, 26472, 15422, 23378, 2439, 10762, 7128, 33634, 29864, 7286, 10278, 11042, 23661, 23799, 20425, 3947, 23963, 2817, 5132, 15596, 18532, 43218, 10728, 15032, 31189, 11575, 38493, 43660, 35116, 13849, 5897, 46380, 34985, 37766, 97, 40880, 41343, 25060, 16535, 29200, 34062, 44276, 895, 23472, 31327, 42001, 29371, 13367, 17232, 44934, 41900, 43695, 37368, 29776, 24740, 40968, 22933, 25184, 39501, 12328, 2829, 9565, 11928, 38235, 780, 31456, 16472, 24655, 24679, 32447, 46045, 21111, 3560, 4223, 10054, 20817, 24547, 22335, 17771, 41209, 27303, 36043, 28463, 36458, 44092, 28958, 18168, 41020, 2394, 34672, 28764, 16254, 3803, 17123, 43921, 7054, 45736, 4826, 7956, 16336, 44633, 47307, 32818, 13273, 6088, 12322, 30500, 20771, 24285, 38294, 2115, 43997, 4942, 46154, 1507, 1256, 27124, 18362, 12535, 29038, 22605, 9017, 8371, 14502, 2346, 35645, 15720, 3638, 635, 9749, 40524, 20377, 39478, 31365, 45388, 4309, 10390, 24530, 43267, 11487, 41729, 27378, 32351, 45556, 331, 40500, 5501, 29534, 18868, 25270, 19142, 4709, 38480, 41649, 41275, 45492, 11553, 11453, 6197, 44347, 40238, 7525, 22786, 37800, 3629, 44169, 15103, 42087, 32311, 47363, 45627, 7112, 19341, 23756, 3794, 41797, 35973, 9395, 27827, 4775, 24930, 35261, 43171, 26717, 4111, 20711, 38022, 5721, 40757, 38801, 43326, 46702, 4986, 20016, 44929, 43722, 39774, 25109, 16570, 46028, 4229, 47513, 32091, 37576, 33687, 35387, 18681, 3068, 10462, 13595, 8791, 29465, 34831, 2919, 44686, 27537, 27768, 21022, 37520, 47763, 1460, 23521, 45584, 3330, 29236, 31912, 7627, 32738, 3426, 23932, 32374, 25353, 10075, 38439, 38280, 2215, 22173, 30557, 45244, 22707, 38545, 45905, 18136, 25657, 16830, 23825, 5836, 21964, 1835, 24812, 20451, 19743, 43994, 12624, 19889, 36786, 11080, 24106, 9299, 19343, 38860, 7173, 14791, 45171, 20340, 41540, 42956, 43045, 24891, 9554, 41518, 2674, 2475, 4488, 28155, 4168, 47361, 22475, 39426, 41442, 11931, 20674, 7429, 29048, 38648, 28240, 40922, 43074, 12452, 23435, 9657, 37209, 42617, 27471, 11665, 7340, 27715, 33522, 6369, 7964, 30257, 27339, 16446, 4604, 8499, 44839, 36605, 37478, 12797, 46329, 45752, 24777, 46515, 23416, 20901, 30043, 27593, 27572, 25452, 17086, 29258, 11964, 20282, 33555, 2039, 41986, 23926, 5186, 28469, 23248, 33365, 32703, 46308, 9122, 20680, 24472, 16765, 21686, 47781, 16773, 10954, 16865, 16150, 33032, 42531, 18993, 25904, 39666, 1696, 37963, 5803, 23982, 1361, 36882, 3276, 21562, 12112, 47932, 43868, 3500, 44175, 2904, 38241, 34917, 35421, 29403, 19449, 8784, 48269, 46134, 31052, 26623, 46369, 30019, 46886, 15476, 29373, 45723, 34582, 15814, 1983, 23881, 26778, 34545, 31088, 4289, 9603, 44264, 31021, 37716, 8788, 43487, 11019, 2093, 14408, 26878, 29146, 2531, 2355, 45772, 22695, 3606, 35905, 8418, 13738, 11001, 36443, 18584, 36336, 40322, 32685, 27835, 38981, 42092, 10593, 37537, 43490, 24574, 7124, 41437, 42183, 2759, 22639, 47379, 17969, 28110, 14193, 7473, 26158, 37695, 16713, 23750, 38898, 13327, 9868, 16436, 46338, 5988, 47617, 31260, 29349, 44323, 26967, 23294, 39357, 46684, 17198, 2042, 16230, 44952, 36719, 35587, 47519, 33198, 10799, 28906, 21952, 8214, 37456, 40910, 7927, 45955, 4427, 47665, 18141, 20749, 20943, 13513, 7660, 11781, 3396, 17084, 6254, 19882, 8472, 42124, 35341, 29972, 12886, 15967, 40743, 14943, 19122, 32390, 35611, 15699, 34167, 6556, 11984, 18829, 19530, 18733, 13645, 25396, 24328, 44269, 6399, 41236, 924, 19968, 39360, 34548, 46668, 44911, 15448, 42706, 31629, 26674, 12536, 19042, 33024, 12775, 35852, 45995, 21917, 22493, 36756, 9648, 3985, 3298, 45077, 18029, 40836, 25071, 40679, 18332, 40941, 33065, 21804, 31041, 46229, 41903, 15965, 36496, 28870, 17465, 43471, 25348, 2279, 39857, 804, 5671, 2691, 16405, 40946, 32219, 48077, 30800, 21795, 21041, 7973, 1029, 9448, 15157, 21893, 6466, 27532, 21849, 24140, 16997, 5576, 40561, 22897, 10482, 29380, 26722, 32729, 32769, 42222, 8858, 26107, 39689, 11410, 27213, 42214, 16342, 24674, 44993, 38417, 15273, 36233, 39341, 8532, 27248, 41785, 13236, 26342, 11680, 34202, 9286, 20095, 38140, 18924, 234, 47938, 5578, 103, 37942, 13473, 19927, 47855, 7504, 39200, 41253, 2918, 811, 28517, 15028, 33627, 11493, 15104, 31477, 562, 47818, 45249, 8478, 43129, 29649, 37167, 3648, 39230, 6619, 25336, 41448, 15428, 2299, 7766, 7245, 435, 17235, 20426, 34454, 23764, 24898, 5309, 45496, 37014, 40491, 16513, 31178, 43002, 2608, 2237, 34669, 45815, 32175, 42540, 41139, 10958, 37257, 40754, 23625, 31392, 11377, 38144, 46180, 8719, 4633, 20485, 28091, 3673, 13585, 22292, 3540, 8810, 14394, 27949, 27866, 42318, 21619, 30046, 3074, 8141, 42143, 11890, 21169, 41994, 23039, 21414, 39416, 44386, 17603, 36109, 19502, 31411, 2089, 44860, 46113, 29750, 26379, 16781, 32387, 27912, 21246, 28618, 29187, 33064, 35172, 28016, 45811, 22001, 8115, 43560, 21, 21757, 48093, 32343, 38100, 23207, 21344, 40228, 28959, 47133, 3572, 2920, 11708, 4781, 29382, 29689, 47982, 14456, 28663, 33272, 27454, 18702, 15201, 20932, 14404, 739, 45206, 35438, 33415, 16135, 2372, 20783, 27113, 38425, 21512, 17827, 37601, 42232, 42428, 35784, 1917, 28222, 3225, 36860, 44666, 12512, 29911, 586, 15921, 13214, 47181, 30034, 4390, 36662, 36823, 26807, 25549, 27450, 26281, 40142, 35824, 5075, 26699, 179, 33090, 5970, 36764, 3806, 20098, 6106, 10776, 23821, 21722, 42164, 39091, 31161, 21435, 41511, 7223, 37899, 13897, 4105, 8894, 48003, 36005, 18670, 29696, 16095, 24036, 39080, 15190, 32698, 16574, 21235, 5347, 38551, 9911, 5569, 1756, 13188, 35284, 28634, 20415, 4250, 39700, 46031, 17722, 17519, 27200, 9224, 17228, 18451, 15374, 14917, 2844, 44487, 45836, 41471, 4278, 14680, 1647, 39949, 15638, 16828, 37246, 42645, 47924, 14044, 7947, 9161, 44547, 32299, 34927, 6555, 25402, 3184, 11689, 31385, 14595, 34200, 42456, 24178, 43840, 4736, 18369, 2090, 8615, 24563, 34839, 40117, 36946, 12486, 46754, 21198, 731, 30729, 18350, 24820, 6079, 12091, 24227, 7783, 42659, 1587, 19585, 38832, 2154, 20122, 40338, 13673, 23890, 5262, 25947, 47554, 20461, 17248, 26719, 10702, 38576, 20403, 1266, 43807, 4048, 27854, 17387, 43273, 30411, 40411, 10686, 19528, 45919, 2575, 532, 19424, 18816, 16362, 22027, 16597, 11124, 6929, 12756, 4514, 42790, 19423, 7200, 11244, 47905, 26915, 31264, 3994, 21895, 38200, 47577, 25239, 10024, 40350, 47365, 16037, 7221, 42298, 8396, 18426, 26246, 18423, 14492, 36210, 11846, 34894, 2447, 4437, 45280, 2900, 46362, 44533, 20751, 10990, 35340, 37254, 8976, 34091, 3877, 324, 8423, 17844, 14976, 19827, 3477, 23917, 23833, 22030, 26770, 777, 10846, 27818, 33975, 3689, 9244, 43930, 319, 16389, 11674, 39623, 39297, 47550, 41562, 26537, 15621, 46714, 27073, 37583, 21939, 10060, 37689, 19800, 35888, 12513, 43138, 13244, 43506, 12923, 36094, 48016, 3559, 2319, 30996, 40885, 39573, 19711, 9540, 30762, 37698, 3486, 24906, 28310, 24551, 30382, 17826, 34776, 34868, 36999, 34723, 33199, 459, 8036, 25580, 39809, 44256, 36271, 24853, 24765, 46123, 11917, 44422, 5267, 32045, 33769, 6141, 36266, 33214, 37810, 18446, 36845, 16879, 39498, 18862, 11424, 3942, 27479, 25076, 8267, 8203, 21763, 11121, 4491, 5618, 5942, 28632, 33112, 30154, 15048, 13898, 173, 25196, 14991, 350, 27564, 31417, 22654, 47170, 18764, 34163, 33160, 24318, 25007, 14903, 23847, 1494, 23092, 19023, 16791, 24290, 5397, 9208, 3914, 5978, 19026, 48175, 36461, 29184, 27141, 33328, 18663, 21037, 44196, 36884, 35335, 31349, 19902, 3531, 23600, 37900, 12152, 31672, 36273, 5946, 17768, 31462, 43877, 14055, 2127, 16631, 14644, 25261, 11533, 4910, 46513, 32153, 10992, 19998, 42093, 11492, 14378, 12235, 5114, 24808, 13913, 3889, 40560, 18560, 13314, 838, 32612, 33560, 39392, 39597, 33558, 3142, 38338, 46828, 33887, 34570, 3076, 8055, 5199, 8685, 39090, 9451, 18164, 4600, 9718, 26490, 2909, 25519, 23088, 17566, 5057, 23795, 35976, 6950, 31183, 33662, 4914, 38994, 11811, 47901, 8829, 30081, 26359, 23151, 27162, 44951, 40143, 11950, 31872, 13410, 43397, 8463, 12987, 47314, 12331, 36253, 20833, 18799, 30655, 38122, 10444, 41784, 45930, 44013, 5809, 6191, 43861, 44932, 25460, 41516, 7926, 14038, 39305, 13007, 40969, 30080, 25598, 46834, 26449, 19454, 33479, 1655, 30738, 15665, 41645, 21042, 16356, 22366, 16365, 10864, 35522, 1012, 46022, 21813, 41990, 661, 32624, 42776, 13213, 40987, 46769, 37521, 2246, 1998, 399, 6845, 39184, 47158, 46794, 13405, 14641, 1814, 41013, 4009, 5902, 9529, 10105, 34969, 36361, 23713, 40827, 37312, 39686, 6294, 45336, 17747, 14355, 31788, 16621, 34031, 25991, 42565, 48044, 17012, 29613, 28560, 31628, 20058, 16502, 33130, 14129, 23026, 35594, 12839, 47695, 12827, 28718, 4489, 3608, 25404, 19951, 37841, 2510, 37527, 45717, 5189, 10995, 32805, 5079, 5465, 31893, 11490, 6270, 188, 38602, 19725, 3722, 17273, 9435, 4362, 40905, 29056, 15259, 44091, 31505, 34504, 30899, 30442, 18941, 2800, 3063, 45596, 20554, 26514, 23887, 9407, 15128, 41996, 40097, 27913, 38645, 32761, 23607, 16082, 6814, 6186, 33249, 45389, 8700, 46860, 47143, 12014, 6400, 28087, 48179, 47187, 36969, 22735, 868, 23490, 7823, 34616, 28258, 39726, 8163, 5722, 18626, 10709, 34896, 27001, 44672, 7104, 2159, 34767, 47017, 14761, 38638, 4654, 20809, 36473, 41192, 35110, 19681, 16928, 40126, 21220, 29157, 33018, 11977, 27757, 11305, 44918, 40877, 25204, 23324, 35034, 43699, 10459, 29849, 3139, 34022, 848, 14685, 14581, 2979, 32718, 31523, 17889, 10779, 31299, 5638, 19623, 44003, 32121, 41619, 16270, 4407, 27987, 24216, 38062, 24729, 34044, 36539, 16822, 16758, 32397, 8359, 7603, 21991, 37255, 39626, 33547, 2235, 45324, 2664, 1994, 11673, 12398, 35881, 28557, 32618, 38021, 9897, 41911, 31697, 28244, 36211, 25570, 46940, 3300, 7922, 7581, 3926, 13681, 318, 33888, 790, 25515, 20271, 12214, 24733, 3077, 22270, 32488, 19125, 18909, 26159, 20075, 14279, 37091, 30236, 17189, 27706, 48073, 21978, 42237, 12899, 38517, 4590, 42505, 9093, 35501, 20944, 31757, 20848, 1956, 15495, 18110, 39786, 299, 8934, 37918, 719, 1719, 19838, 42943, 24204, 19162, 34995, 37715, 39619, 19381, 8716, 28542, 46488, 14886, 31817, 16755, 22653, 19352, 382, 45185, 36341, 33959, 8771, 25489, 452, 32209, 6303, 43662, 32819, 26, 21328, 18845, 23696, 24554, 13477, 22669, 36523, 40488, 41592, 40223, 48011, 9101, 41656, 36467, 9604, 6259, 18211, 1504, 33292, 33528, 5623, 29006, 33907, 9404, 30194, 11264, 27336, 29901, 11454, 7536, 2650, 47441, 37111, 7890, 28104, 8642, 12167, 16550, 26855, 13383, 26691, 43114, 19266, 2836, 13368, 10104, 28030, 7842, 19285, 42845, 21112, 1839, 16248, 4129, 22601, 20323, 26690, 9769, 42390, 1656, 11076, 10475, 20781, 9083, 15982, 47222, 8170, 12807, 35529, 35959, 23273, 36846, 28931, 16054, 12491, 6727, 23212, 24289, 11082, 30401, 19482, 10606, 46384, 2902, 17674, 19597, 22858, 5084, 25266, 18715, 2669, 47691, 21688, 42887, 33899, 10252, 30449, 34350, 17708, 43305, 24865, 45810, 9908, 11751, 3949, 23330, 46804, 37780, 41227, 4421, 43546, 37751, 35257, 47327, 47587, 8364, 33690, 23760, 28743, 19189, 29086, 17761, 7455, 12698, 24372, 4585, 22721, 36208, 42204, 10717, 13052, 7556, 23441, 48303, 21542, 24795, 47401, 5357, 109, 45378, 12709, 43195, 41350, 26374, 16202, 43285, 31663, 39479, 4691, 46857, 33200, 33657, 817, 5111, 4327, 35854, 20721, 16898, 23857, 42102, 10883, 19757, 39281, 47856, 30310, 20027, 46341, 29522, 6418, 21866, 18546, 22782, 40179, 20269, 5841, 18612, 29986, 26819, 9541, 9862, 11050, 3785, 43522, 3031, 27094, 33159, 38078, 44220, 39523, 33782, 14522, 7970, 9292, 21209, 11308, 11506, 45964, 10099, 5552, 40580, 30727, 16835, 46463, 18669, 20378, 30547, 15775, 41224, 13353, 39837, 28291, 27066, 27106, 24512, 44100, 40596, 35685, 46493, 15223, 12776, 39535, 34528, 2802, 22604, 38092, 6614, 43939, 25823, 33009, 40906, 27274, 45920, 130, 14896, 17607, 12259, 34049, 38840, 13795, 14957, 37814, 28002, 43007, 27978, 35351, 32382, 28061, 41347, 6990, 45883, 18856, 28615, 19193, 2258, 14262, 36429, 36133, 16664, 12578, 5591, 19517, 34972, 14230, 21027, 41599, 33313, 11317, 22454, 38244, 10076, 21103, 20699, 37967, 38699, 21570, 46490, 37001, 41840, 36573, 31434, 16739, 14113, 32318, 32103, 21257, 3195, 19643, 2424, 29877, 31167, 46783, 13560, 15836, 46607, 47310, 30828, 7583, 39865, 12272, 42814, 2419, 15890, 15313, 5898, 10847, 16695, 18888, 19957, 35363, 1158, 39553, 22433, 18817, 47247, 23714, 33161, 45131, 3968, 18718, 42464, 7103, 21625, 10985, 14210, 34694, 42575, 15676, 38752, 9941, 13928, 17460, 13282, 2624, 3953, 41750, 34107, 28993, 4598, 25844, 2725, 23352, 18434, 2507, 44972, 9981, 46619, 42348, 42620, 17640, 32956, 39822, 30274, 20600, 37857, 14460, 40138, 30402, 47919, 3331, 13629, 30723, 10435, 27031, 14900, 7913, 24588, 22378, 462, 37472, 33227, 41095, 46910, 19408, 38337, 20695, 44905, 41423, 14582, 10155, 43944, 17163, 42651, 47920, 8048, 4060, 6838, 7962, 47103, 12065, 45932, 43112, 11783, 20627, 35441, 5604, 32392, 18956, 22845, 

In [ ]:
lr2 = regression(method='gd')
lr2.fit(x_train,y_tarin)
print(lr2.w)

[ -7.1813823   -9.57570946 -12.98029995  -4.12044017  -3.60098964
  -3.52884143  -3.32103543  -3.49365286  -3.34657804  -2.85502888
  -2.60739469  -2.26600357  -1.29633733  -1.57481697  -1.09285193
  -0.91669477  -0.94848614  -0.71595094  -0.53241258  -0.48872002
  -0.36739656  -0.42217389  -0.41656548  -0.30175215]

In [ ]:
lr1 = regression(method='analytic')
lr1.fit(x_train,y_tarin)
print(lr1.w)

[ 594.16774449 1575.61950639  463.19262189  225.94956994 -171.13946822
  -82.29562883  155.22419075  619.24285788  149.26531835 -164.70166353
 -219.63365493  243.62361178  -25.48940922  456.82108237 -105.10019517
  -91.9596842   121.56421258 -228.87031369  -38.52624836   34.8774644
 -363.80845622 -114.37794051  175.4540985    36.24622721]

In [ ]:
model = regression()
model.fit(x_train, y_tarin)
model.w

KeyError: '[1270, 48361, 10115, 5098, 28942, 16139, 41754, 38872, 41147, 3107, 46657, 32999, 23487, 34711, 24352, 22202, 3435, 22353, 15416, 47795, 7419, 34628, 37237, 43600, 4089, 22983, 27299, 27771, 39060, 34207, 17479, 29431, 33353, 13622, 10457, 17344, 30315, 22761, 34515, 37346, 39823, 2553, 27380, 22092, 22921, 31607, 36684, 9463, 16179, 3630, 39965, 20229, 29701, 3078, 46968, 1098, 29266, 30681, 16201, 3992, 6872, 10840, 8298, 21309, 21439, 3343, 35318, 47411, 16448, 33929, 24619, 47473, 18713, 7, 45861, 31795, 3525, 7746, 29260, 41424, 29563, 43088, 33341, 36824, 5033, 35208, 31619, 11725, 32081, 34810, 18022, 16099, 19015, 23689, 18929, 31743, 29028, 12684, 3203, 17334, 6726, 5004, 9378, 43105, 11922, 29473, 3366, 4707, 46455, 5896, 43951, 9217, 18974, 41613, 20469, 23784, 42722, 11294, 16699, 35305, 40356, 36623, 24470, 42580, 38978, 4238, 25429, 46411, 2657, 33857, 17210, 15350, 18591, 16319, 20006, 29189, 35113, 24333, 44362, 39491, 10461, 42946, 1575, 40731, 38342, 16391, 33406, 16524, 16837, 8022, 39085, 6612, 6655, 35385, 13985, 43481, 25267, 37100, 21216, 45161, 180, 19170, 29085, 31091, 8266, 42646, 22343, 44907, 24026, 48306, 40400, 32773, 29239, 27929, 27766, 39443, 34122, 1524, 19731, 18692, 4378, 12525, 46645, 6715, 1919, 44228, 1832, 43266, 39500, 21212, 3857, 37974, 2494, 46610, 24108, 15293, 2994, 19090, 39069, 36110, 46161, 12821, 26995, 6886, 13351, 27992, 32281, 44646, 24464, 30180, 21752, 4881, 6993, 24336, 10292, 31481, 1616, 2828, 19256, 27256, 48131, 13362, 30149, 36991, 32329, 5457, 22662, 24261, 8037, 18939, 43000, 21791, 26259, 25813, 29876, 33460, 32611, 31441, 26948, 20059, 12082, 22559, 29909, 17358, 28428, 43191, 23417, 40066, 4776, 34721, 46421, 37124, 24862, 1642, 35198, 3576, 39877, 34576, 1419, 46106, 20115, 36640, 5635, 4352, 1331, 48032, 16276, 23735, 22498, 35860, 30606, 7792, 31860, 38900, 30849, 38262, 27131, 15702, 34220, 48310, 4419, 10675, 10719, 3016, 8039, 213, 28694, 43029, 12013, 42635, 9373, 38485, 3368, 39946, 41894, 43583, 24787, 14739, 15762, 45634, 11809, 1900, 33812, 6133, 1355, 42129, 28058, 18642, 40366, 5929, 34958, 21109, 47384, 24741, 46813, 47622, 37913, 10389, 47664, 9028, 22171, 22234, 20313, 9036, 46974, 14019, 9192, 44190, 32466, 7577, 46309, 40196, 3552, 41801, 43941, 37347, 31248, 31589, 9890, 13211, 35014, 16403, 32458, 44029, 46653, 31112, 18156, 9816, 20277, 24367, 46376, 14367, 31155, 45949, 42690, 47460, 16182, 17301, 43566, 19035, 38970, 25664, 28777, 33896, 41749, 18703, 47812, 44048, 41848, 13637, 44243, 45137, 8271, 36459, 42525, 2885, 12100, 44023, 4304, 12890, 33679, 33709, 46692, 31676, 31312, 39698, 14319, 45265, 8903, 34774, 33525, 23078, 19422, 43817, 25128, 47221, 7445, 25088, 30579, 10186, 14847, 10798, 43902, 10939, 21025, 24606, 19296, 10441, 39464, 32789, 46962, 17138, 37896, 5080, 24, 20708, 29061, 3603, 4152, 40933, 2856, 9088, 9567, 36213, 37860, 38353, 27678, 14495, 43544, 8573, 5028, 3549, 306, 46980, 48117, 45382, 30679, 11357, 28290, 21081, 34004, 21189, 9346, 19601, 4943, 1615, 19527, 10940, 38805, 10884, 8865, 44587, 48326, 17667, 643, 2996, 3334, 43933, 982, 4017, 45755, 9050, 35547, 42816, 5156, 33596, 3028, 11844, 24430, 33684, 25523, 8664, 17254, 7444, 42528, 20306, 26275, 32016, 4120, 11670, 8313, 48262, 39904, 31479, 31267, 34550, 13790, 23532, 31127, 3703, 12356, 1005, 20885, 37044, 19863, 32179, 25539, 10904, 42813, 38629, 45066, 16239, 44891, 22212, 3495, 30593, 25550, 18456, 22436, 23734, 9107, 23599, 42459, 22, 34717, 42247, 39108, 48342, 39356, 3221, 39364, 31042, 10132, 35754, 39137, 47973, 18325, 35301, 27390, 28362, 41092, 27742, 45934, 45944, 28652, 16387, 17408, 24239, 27428, 31594, 29868, 8667, 40686, 7533, 6524, 42366, 28627, 12192, 28603, 30527, 14445, 33240, 25935, 37469, 12291, 22221, 41231, 19022, 25839, 14588, 8455, 31207, 37808, 40182, 14934, 32582, 20109, 47269, 30995, 12191, 16220, 38597, 34886, 32519, 2641, 14987, 33376, 14096, 15589, 26761, 39160, 42732, 44262, 8028, 29610, 31747, 25621, 43559, 1931, 37992, 40642, 13009, 33685, 37374, 26276, 46547, 6914, 37629, 41675, 44498, 9090, 11850, 2274, 9475, 1990, 23616, 36781, 31409, 10894, 27825, 38830, 26162, 14286, 30618, 23494, 19897, 19366, 7979, 39474, 38117, 27239, 23468, 28204, 26041, 10502, 18990, 37861, 44284, 30816, 5899, 25159, 47355, 13837, 35265, 2647, 2402, 30000, 25496, 24517, 30575, 24762, 31382, 34358, 34137, 2260, 47703, 25186, 5608, 36927, 22322, 38739, 16556, 21860, 27047, 45073, 39788, 8027, 33971, 36521, 9302, 48237, 46291, 41397, 45452, 35090, 47452, 8570, 21051, 31451, 47245, 22468, 12722, 40236, 6329, 41049, 13703, 4318, 44942, 34146, 45866, 25112, 45399, 15149, 18812, 33311, 21122, 26827, 21330, 8519, 42989, 23186, 22187, 3590, 22887, 21099, 4464, 29002, 1724, 5436, 33132, 20385, 6567, 47486, 37275, 20741, 33826, 21156, 14553, 8003, 23049, 37279, 22959, 41263, 12298, 39690, 47508, 40921, 27841, 7130, 46890, 48119, 46675, 14752, 44593, 6179, 2389, 14904, 24967, 45708, 35765, 966, 7082, 34640, 42914, 8389, 25185, 18087, 46761, 6049, 18295, 1104, 4295, 13074, 40849, 45321, 14983, 44842, 6582, 2052, 24989, 9156, 26489, 3018, 19579, 17551, 17137, 42980, 48251, 38483, 23321, 44251, 35157, 29765, 37958, 14605, 20525, 40395, 47286, 42841, 36190, 11908, 30505, 24452, 27311, 32294, 39937, 42457, 3744, 43215, 24694, 22866, 34818, 42463, 29763, 47910, 5058, 36524, 18620, 14631, 14016, 45663, 3065, 43562, 15897, 39915, 6910, 40176, 18936, 14180, 19873, 46458, 38796, 33593, 43401, 10688, 18964, 4054, 44542, 37664, 31604, 14975, 37727, 12853, 12945, 31072, 372, 25797, 36250, 19411, 44755, 13737, 9321, 37376, 14347, 13675, 9189, 3178, 30338, 1205, 24149, 35634, 955, 9089, 37459, 11025, 19811, 15245, 15126, 46606, 31086, 6544, 20735, 20091, 17716, 29102, 47671, 48337, 543, 10658, 12035, 4321, 4503, 32122, 20912, 47976, 31722, 18175, 19084, 2087, 16538, 23912, 28956, 41753, 45021, 40073, 40995, 42420, 31101, 2633, 37968, 28644, 10744, 23253, 41141, 15208, 44510, 33476, 29150, 28655, 37525, 10088, 22297, 15106, 10337, 44476, 20855, 3349, 13013, 43970, 14085, 38741, 10951, 35631, 31276, 23173, 405, 41961, 8292, 38479, 28805, 26214, 18861, 9659, 24002, 20060, 11923, 1865, 31025, 26960, 32632, 8400, 44876, 18885, 24566, 8246, 14110, 3323, 19075, 6119, 20225, 46169, 32127, 43295, 46149, 40477, 46468, 28621, 12953, 21818, 43361, 39197, 42234, 13996, 14159, 1555, 10512, 24111, 23530, 36652, 44849, 13885, 42535, 13905, 21648, 27636, 21164, 6307, 34558, 34128, 31660, 12427, 33257, 18978, 20687, 39165, 13312, 28771, 10638, 41159, 39555, 25434, 31730, 5503, 44199, 30773, 14065, 209, 35096, 12976, 39896, 3027, 19432, 30826, 3663, 33496, 9272, 15473, 46027, 19176, 1863, 3826, 29938, 35612, 43243, 15644, 33016, 12271, 40749, 38265, 42740, 16483, 7452, 8610, 37849, 4647, 34574, 29405, 45475, 42805, 13909, 10016, 20998, 16056, 4891, 2980, 2199, 45619, 48028, 1726, 19828, 37033, 25074, 301, 8522, 45226, 25925, 21836, 25385, 30774, 32011, 29387, 30045, 7045, 28095, 16867, 44619, 33046, 35595, 11998, 45541, 347, 2303, 2600, 13120, 44259, 39778, 40019, 4052, 38451, 17644, 16567, 39363, 17264, 42803, 23019, 37874, 24300, 21515, 22142, 11147, 8416, 40616, 39678, 30597, 38812, 22040, 30823, 3288, 33339, 18991, 35593, 4348, 30535, 10739, 9854, 24320, 45043, 36057, 27317, 14602, 26209, 32914, 1248, 9079, 26472, 15422, 23378, 2439, 10762, 7128, 33634, 29864, 7286, 10278, 11042, 23661, 23799, 20425, 3947, 23963, 2817, 5132, 15596, 18532, 43218, 10728, 15032, 31189, 11575, 38493, 43660, 35116, 13849, 5897, 46380, 34985, 37766, 97, 40880, 41343, 25060, 16535, 29200, 34062, 44276, 895, 23472, 31327, 42001, 29371, 13367, 17232, 44934, 41900, 43695, 37368, 29776, 24740, 40968, 22933, 25184, 39501, 12328, 2829, 9565, 11928, 38235, 780, 31456, 16472, 24655, 24679, 32447, 46045, 21111, 3560, 4223, 10054, 20817, 24547, 22335, 17771, 41209, 27303, 36043, 28463, 36458, 44092, 28958, 18168, 41020, 2394, 34672, 28764, 16254, 3803, 17123, 43921, 7054, 45736, 4826, 7956, 16336, 44633, 47307, 32818, 13273, 6088, 12322, 30500, 20771, 24285, 38294, 2115, 43997, 4942, 46154, 1507, 1256, 27124, 18362, 12535, 29038, 22605, 9017, 8371, 14502, 2346, 35645, 15720, 3638, 635, 9749, 40524, 20377, 39478, 31365, 45388, 4309, 10390, 24530, 43267, 11487, 41729, 27378, 32351, 45556, 331, 40500, 5501, 29534, 18868, 25270, 19142, 4709, 38480, 41649, 41275, 45492, 11553, 11453, 6197, 44347, 40238, 7525, 22786, 37800, 3629, 44169, 15103, 42087, 32311, 47363, 45627, 7112, 19341, 23756, 3794, 41797, 35973, 9395, 27827, 4775, 24930, 35261, 43171, 26717, 4111, 20711, 38022, 5721, 40757, 38801, 43326, 46702, 4986, 20016, 44929, 43722, 39774, 25109, 16570, 46028, 4229, 47513, 32091, 37576, 33687, 35387, 18681, 3068, 10462, 13595, 8791, 29465, 34831, 2919, 44686, 27537, 27768, 21022, 37520, 47763, 1460, 23521, 45584, 3330, 29236, 31912, 7627, 32738, 3426, 23932, 32374, 25353, 10075, 38439, 38280, 2215, 22173, 30557, 45244, 22707, 38545, 45905, 18136, 25657, 16830, 23825, 5836, 21964, 1835, 24812, 20451, 19743, 43994, 12624, 19889, 36786, 11080, 24106, 9299, 19343, 38860, 7173, 14791, 45171, 20340, 41540, 42956, 43045, 24891, 9554, 41518, 2674, 2475, 4488, 28155, 4168, 47361, 22475, 39426, 41442, 11931, 20674, 7429, 29048, 38648, 28240, 40922, 43074, 12452, 23435, 9657, 37209, 42617, 27471, 11665, 7340, 27715, 33522, 6369, 7964, 30257, 27339, 16446, 4604, 8499, 44839, 36605, 37478, 12797, 46329, 45752, 24777, 46515, 23416, 20901, 30043, 27593, 27572, 25452, 17086, 29258, 11964, 20282, 33555, 2039, 41986, 23926, 5186, 28469, 23248, 33365, 32703, 46308, 9122, 20680, 24472, 16765, 21686, 47781, 16773, 10954, 16865, 16150, 33032, 42531, 18993, 25904, 39666, 1696, 37963, 5803, 23982, 1361, 36882, 3276, 21562, 12112, 47932, 43868, 3500, 44175, 2904, 38241, 34917, 35421, 29403, 19449, 8784, 48269, 46134, 31052, 26623, 46369, 30019, 46886, 15476, 29373, 45723, 34582, 15814, 1983, 23881, 26778, 34545, 31088, 4289, 9603, 44264, 31021, 37716, 8788, 43487, 11019, 2093, 14408, 26878, 29146, 2531, 2355, 45772, 22695, 3606, 35905, 8418, 13738, 11001, 36443, 18584, 36336, 40322, 32685, 27835, 38981, 42092, 10593, 37537, 43490, 24574, 7124, 41437, 42183, 2759, 22639, 47379, 17969, 28110, 14193, 7473, 26158, 37695, 16713, 23750, 38898, 13327, 9868, 16436, 46338, 5988, 47617, 31260, 29349, 44323, 26967, 23294, 39357, 46684, 17198, 2042, 16230, 44952, 36719, 35587, 47519, 33198, 10799, 28906, 21952, 8214, 37456, 40910, 7927, 45955, 4427, 47665, 18141, 20749, 20943, 13513, 7660, 11781, 3396, 17084, 6254, 19882, 8472, 42124, 35341, 29972, 12886, 15967, 40743, 14943, 19122, 32390, 35611, 15699, 34167, 6556, 11984, 18829, 19530, 18733, 13645, 25396, 24328, 44269, 6399, 41236, 924, 19968, 39360, 34548, 46668, 44911, 15448, 42706, 31629, 26674, 12536, 19042, 33024, 12775, 35852, 45995, 21917, 22493, 36756, 9648, 3985, 3298, 45077, 18029, 40836, 25071, 40679, 18332, 40941, 33065, 21804, 31041, 46229, 41903, 15965, 36496, 28870, 17465, 43471, 25348, 2279, 39857, 804, 5671, 2691, 16405, 40946, 32219, 48077, 30800, 21795, 21041, 7973, 1029, 9448, 15157, 21893, 6466, 27532, 21849, 24140, 16997, 5576, 40561, 22897, 10482, 29380, 26722, 32729, 32769, 42222, 8858, 26107, 39689, 11410, 27213, 42214, 16342, 24674, 44993, 38417, 15273, 36233, 39341, 8532, 27248, 41785, 13236, 26342, 11680, 34202, 9286, 20095, 38140, 18924, 234, 47938, 5578, 103, 37942, 13473, 19927, 47855, 7504, 39200, 41253, 2918, 811, 28517, 15028, 33627, 11493, 15104, 31477, 562, 47818, 45249, 8478, 43129, 29649, 37167, 3648, 39230, 6619, 25336, 41448, 15428, 2299, 7766, 7245, 435, 17235, 20426, 34454, 23764, 24898, 5309, 45496, 37014, 40491, 16513, 31178, 43002, 2608, 2237, 34669, 45815, 32175, 42540, 41139, 10958, 37257, 40754, 23625, 31392, 11377, 38144, 46180, 8719, 4633, 20485, 28091, 3673, 13585, 22292, 3540, 8810, 14394, 27949, 27866, 42318, 21619, 30046, 3074, 8141, 42143, 11890, 21169, 41994, 23039, 21414, 39416, 44386, 17603, 36109, 19502, 31411, 2089, 44860, 46113, 29750, 26379, 16781, 32387, 27912, 21246, 28618, 29187, 33064, 35172, 28016, 45811, 22001, 8115, 43560, 21, 21757, 48093, 32343, 38100, 23207, 21344, 40228, 28959, 47133, 3572, 2920, 11708, 4781, 29382, 29689, 47982, 14456, 28663, 33272, 27454, 18702, 15201, 20932, 14404, 739, 45206, 35438, 33415, 16135, 2372, 20783, 27113, 38425, 21512, 17827, 37601, 42232, 42428, 35784, 1917, 28222, 3225, 36860, 44666, 12512, 29911, 586, 15921, 13214, 47181, 30034, 4390, 36662, 36823, 26807, 25549, 27450, 26281, 40142, 35824, 5075, 26699, 179, 33090, 5970, 36764, 3806, 20098, 6106, 10776, 23821, 21722, 42164, 39091, 31161, 21435, 41511, 7223, 37899, 13897, 4105, 8894, 48003, 36005, 18670, 29696, 16095, 24036, 39080, 15190, 32698, 16574, 21235, 5347, 38551, 9911, 5569, 1756, 13188, 35284, 28634, 20415, 4250, 39700, 46031, 17722, 17519, 27200, 9224, 17228, 18451, 15374, 14917, 2844, 44487, 45836, 41471, 4278, 14680, 1647, 39949, 15638, 16828, 37246, 42645, 47924, 14044, 7947, 9161, 44547, 32299, 34927, 6555, 25402, 3184, 11689, 31385, 14595, 34200, 42456, 24178, 43840, 4736, 18369, 2090, 8615, 24563, 34839, 40117, 36946, 12486, 46754, 21198, 731, 30729, 18350, 24820, 6079, 12091, 24227, 7783, 42659, 1587, 19585, 38832, 2154, 20122, 40338, 13673, 23890, 5262, 25947, 47554, 20461, 17248, 26719, 10702, 38576, 20403, 1266, 43807, 4048, 27854, 17387, 43273, 30411, 40411, 10686, 19528, 45919, 2575, 532, 19424, 18816, 16362, 22027, 16597, 11124, 6929, 12756, 4514, 42790, 19423, 7200, 11244, 47905, 26915, 31264, 3994, 21895, 38200, 47577, 25239, 10024, 40350, 47365, 16037, 7221, 42298, 8396, 18426, 26246, 18423, 14492, 36210, 11846, 34894, 2447, 4437, 45280, 2900, 46362, 44533, 20751, 10990, 35340, 37254, 8976, 34091, 3877, 324, 8423, 17844, 14976, 19827, 3477, 23917, 23833, 22030, 26770, 777, 10846, 27818, 33975, 3689, 9244, 43930, 319, 16389, 11674, 39623, 39297, 47550, 41562, 26537, 15621, 46714, 27073, 37583, 21939, 10060, 37689, 19800, 35888, 12513, 43138, 13244, 43506, 12923, 36094, 48016, 3559, 2319, 30996, 40885, 39573, 19711, 9540, 30762, 37698, 3486, 24906, 28310, 24551, 30382, 17826, 34776, 34868, 36999, 34723, 33199, 459, 8036, 25580, 39809, 44256, 36271, 24853, 24765, 46123, 11917, 44422, 5267, 32045, 33769, 6141, 36266, 33214, 37810, 18446, 36845, 16879, 39498, 18862, 11424, 3942, 27479, 25076, 8267, 8203, 21763, 11121, 4491, 5618, 5942, 28632, 33112, 30154, 15048, 13898, 173, 25196, 14991, 350, 27564, 31417, 22654, 47170, 18764, 34163, 33160, 24318, 25007, 14903, 23847, 1494, 23092, 19023, 16791, 24290, 5397, 9208, 3914, 5978, 19026, 48175, 36461, 29184, 27141, 33328, 18663, 21037, 44196, 36884, 35335, 31349, 19902, 3531, 23600, 37900, 12152, 31672, 36273, 5946, 17768, 31462, 43877, 14055, 2127, 16631, 14644, 25261, 11533, 4910, 46513, 32153, 10992, 19998, 42093, 11492, 14378, 12235, 5114, 24808, 13913, 3889, 40560, 18560, 13314, 838, 32612, 33560, 39392, 39597, 33558, 3142, 38338, 46828, 33887, 34570, 3076, 8055, 5199, 8685, 39090, 9451, 18164, 4600, 9718, 26490, 2909, 25519, 23088, 17566, 5057, 23795, 35976, 6950, 31183, 33662, 4914, 38994, 11811, 47901, 8829, 30081, 26359, 23151, 27162, 44951, 40143, 11950, 31872, 13410, 43397, 8463, 12987, 47314, 12331, 36253, 20833, 18799, 30655, 38122, 10444, 41784, 45930, 44013, 5809, 6191, 43861, 44932, 25460, 41516, 7926, 14038, 39305, 13007, 40969, 30080, 25598, 46834, 26449, 19454, 33479, 1655, 30738, 15665, 41645, 21042, 16356, 22366, 16365, 10864, 35522, 1012, 46022, 21813, 41990, 661, 32624, 42776, 13213, 40987, 46769, 37521, 2246, 1998, 399, 6845, 39184, 47158, 46794, 13405, 14641, 1814, 41013, 4009, 5902, 9529, 10105, 34969, 36361, 23713, 40827, 37312, 39686, 6294, 45336, 17747, 14355, 31788, 16621, 34031, 25991, 42565, 48044, 17012, 29613, 28560, 31628, 20058, 16502, 33130, 14129, 23026, 35594, 12839, 47695, 12827, 28718, 4489, 3608, 25404, 19951, 37841, 2510, 37527, 45717, 5189, 10995, 32805, 5079, 5465, 31893, 11490, 6270, 188, 38602, 19725, 3722, 17273, 9435, 4362, 40905, 29056, 15259, 44091, 31505, 34504, 30899, 30442, 18941, 2800, 3063, 45596, 20554, 26514, 23887, 9407, 15128, 41996, 40097, 27913, 38645, 32761, 23607, 16082, 6814, 6186, 33249, 45389, 8700, 46860, 47143, 12014, 6400, 28087, 48179, 47187, 36969, 22735, 868, 23490, 7823, 34616, 28258, 39726, 8163, 5722, 18626, 10709, 34896, 27001, 44672, 7104, 2159, 34767, 47017, 14761, 38638, 4654, 20809, 36473, 41192, 35110, 19681, 16928, 40126, 21220, 29157, 33018, 11977, 27757, 11305, 44918, 40877, 25204, 23324, 35034, 43699, 10459, 29849, 3139, 34022, 848, 14685, 14581, 2979, 32718, 31523, 17889, 10779, 31299, 5638, 19623, 44003, 32121, 41619, 16270, 4407, 27987, 24216, 38062, 24729, 34044, 36539, 16822, 16758, 32397, 8359, 7603, 21991, 37255, 39626, 33547, 2235, 45324, 2664, 1994, 11673, 12398, 35881, 28557, 32618, 38021, 9897, 41911, 31697, 28244, 36211, 25570, 46940, 3300, 7922, 7581, 3926, 13681, 318, 33888, 790, 25515, 20271, 12214, 24733, 3077, 22270, 32488, 19125, 18909, 26159, 20075, 14279, 37091, 30236, 17189, 27706, 48073, 21978, 42237, 12899, 38517, 4590, 42505, 9093, 35501, 20944, 31757, 20848, 1956, 15495, 18110, 39786, 299, 8934, 37918, 719, 1719, 19838, 42943, 24204, 19162, 34995, 37715, 39619, 19381, 8716, 28542, 46488, 14886, 31817, 16755, 22653, 19352, 382, 45185, 36341, 33959, 8771, 25489, 452, 32209, 6303, 43662, 32819, 26, 21328, 18845, 23696, 24554, 13477, 22669, 36523, 40488, 41592, 40223, 48011, 9101, 41656, 36467, 9604, 6259, 18211, 1504, 33292, 33528, 5623, 29006, 33907, 9404, 30194, 11264, 27336, 29901, 11454, 7536, 2650, 47441, 37111, 7890, 28104, 8642, 12167, 16550, 26855, 13383, 26691, 43114, 19266, 2836, 13368, 10104, 28030, 7842, 19285, 42845, 21112, 1839, 16248, 4129, 22601, 20323, 26690, 9769, 42390, 1656, 11076, 10475, 20781, 9083, 15982, 47222, 8170, 12807, 35529, 35959, 23273, 36846, 28931, 16054, 12491, 6727, 23212, 24289, 11082, 30401, 19482, 10606, 46384, 2902, 17674, 19597, 22858, 5084, 25266, 18715, 2669, 47691, 21688, 42887, 33899, 10252, 30449, 34350, 17708, 43305, 24865, 45810, 9908, 11751, 3949, 23330, 46804, 37780, 41227, 4421, 43546, 37751, 35257, 47327, 47587, 8364, 33690, 23760, 28743, 19189, 29086, 17761, 7455, 12698, 24372, 4585, 22721, 36208, 42204, 10717, 13052, 7556, 23441, 48303, 21542, 24795, 47401, 5357, 109, 45378, 12709, 43195, 41350, 26374, 16202, 43285, 31663, 39479, 4691, 46857, 33200, 33657, 817, 5111, 4327, 35854, 20721, 16898, 23857, 42102, 10883, 19757, 39281, 47856, 30310, 20027, 46341, 29522, 6418, 21866, 18546, 22782, 40179, 20269, 5841, 18612, 29986, 26819, 9541, 9862, 11050, 3785, 43522, 3031, 27094, 33159, 38078, 44220, 39523, 33782, 14522, 7970, 9292, 21209, 11308, 11506, 45964, 10099, 5552, 40580, 30727, 16835, 46463, 18669, 20378, 30547, 15775, 41224, 13353, 39837, 28291, 27066, 27106, 24512, 44100, 40596, 35685, 46493, 15223, 12776, 39535, 34528, 2802, 22604, 38092, 6614, 43939, 25823, 33009, 40906, 27274, 45920, 130, 14896, 17607, 12259, 34049, 38840, 13795, 14957, 37814, 28002, 43007, 27978, 35351, 32382, 28061, 41347, 6990, 45883, 18856, 28615, 19193, 2258, 14262, 36429, 36133, 16664, 12578, 5591, 19517, 34972, 14230, 21027, 41599, 33313, 11317, 22454, 38244, 10076, 21103, 20699, 37967, 38699, 21570, 46490, 37001, 41840, 36573, 31434, 16739, 14113, 32318, 32103, 21257, 3195, 19643, 2424, 29877, 31167, 46783, 13560, 15836, 46607, 47310, 30828, 7583, 39865, 12272, 42814, 2419, 15890, 15313, 5898, 10847, 16695, 18888, 19957, 35363, 1158, 39553, 22433, 18817, 47247, 23714, 33161, 45131, 3968, 18718, 42464, 7103, 21625, 10985, 14210, 34694, 42575, 15676, 38752, 9941, 13928, 17460, 13282, 2624, 3953, 41750, 34107, 28993, 4598, 25844, 2725, 23352, 18434, 2507, 44972, 9981, 46619, 42348, 42620, 17640, 32956, 39822, 30274, 20600, 37857, 14460, 40138, 30402, 47919, 3331, 13629, 30723, 10435, 27031, 14900, 7913, 24588, 22378, 462, 37472, 33227, 41095, 46910, 19408, 38337, 20695, 44905, 41423, 14582, 10155, 43944, 17163, 42651, 47920, 8048, 4060, 6838, 7962, 47103, 12065, 45932, 43112, 11783, 20627, 35441, 5604, 32392, 18956, 22845, 

In [ ]:
ytrue = np.array(y_tarin).reshape((-1,1))
ypred = np.array(y_test).reshape((-1,1))

In [ ]:
def r2(y_true ,y_pred):
    sse_re = np.sum((y_true - y_pred)** 2)
    sse_tot = np.sum((y_true - np.mean(y_true))** 2)
    if sse_tot == 0 :
        return 1
    else :
        return 1 - (sse_re / sse_tot)
def rmse(ytrue, ypred):
    n = len(ytrue)
    mse = 1/n * np.sum((ytrue - ypred)**2)
    return np.sqrt(mse)
def mae(ytrue,ypred):
    n  = len(ytrue )
    mae = np.sum(np.abs(ytrue - ypred)) / n
    return mae

In [ ]:
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(X_test)

In [ ]:
print(f"R2: {r2(y_true=y_tarin, y_pred=y_train_pred)}")
print(f"MAE: {mae(y_tarin, y_train_pred)}")
print(f"RMSE: {rmse(y_tarin, y_train_pred)}")

R2: -4.905807826642819
MAE: 3538.6368879059096
RMSE: 3882.5797943859275